import sys
import os
import json
import urllib.request
import urllib.parse
import time
import re
from pathlib import Path

# Always resolve paths relative to this script's location, not the CWD.
SCRIPT_DIR = Path(__file__).resolve().parent


def search_pubmed(query: str):
    url = (
        f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
        f"?db=pubmed&term={urllib.parse.quote(query)}&retmode=json"
    )
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            idlist = data.get("esearchresult", {}).get("idlist", [])
            return idlist
    except Exception:
        return []


def search_ntrs(query: str):
    # NTRS search API
    url = f"https://ntrs.nasa.gov/api/citations/search?q={urllib.parse.quote(query)}"
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            results = data.get("results", [])
            return [res.get("id") for res in results if res.get("id")]
    except Exception:
        return []


def _parse_failed_from_report(report_path: Path) -> list[str]:
    """Extract identifiers (DOIs or titles) that failed from a Relatório.txt.

    The report format generated by generate_detailed_report() marks failures
    with ``Status: não encontrado`` or ``Status: requisição negada`` (not the
    legacy ``[NÃO ENCONTRADO]`` marker used in the old code).
    """
    if not report_path.exists():
        return []

    failed: list[str] = []
    current_id: str | None = None
    current_failed = False

    with open(report_path, "r", encoding="utf-8", errors="replace") as f:
        for raw_line in f:
            line = raw_line.strip()

            # Detect the start of a new entry (DOI: or Título:)
            doi_match = re.match(r"^DOI:\s*(.+)$", line, re.IGNORECASE)
            title_match = re.match(r"^T[íi]tulo:\s*(.+)$", line, re.IGNORECASE)
            if doi_match:
                # Save previous entry if it was a failure
                if current_id and current_failed:
                    failed.append(current_id)
                current_id = doi_match.group(1).strip()
                current_failed = False
            elif title_match:
                if current_id and current_failed:
                    failed.append(current_id)
                current_id = title_match.group(1).strip()
                current_failed = False

            # Detect failure status lines
            if re.search(r"Status:\s*(não encontrado|requisição negada|not.found)", line, re.IGNORECASE):
                current_failed = True
            # Legacy marker kept for backwards compat
            if "[NÃO ENCONTRADO]" in line:
                current_failed = True

    # Don't forget the last entry
    if current_id and current_failed:
        failed.append(current_id)

    return failed


def run_deep_search():
    print("=" * 60)
    print("🚀 INICIANDO BUSCA PROFUNDA (PubMed & NASA NTRS)")
    print("=" * 60)

    failed_dois: list[str] = []
    failed_titles: list[str] = []

    # Bug fix #4b — read reports from SCRIPT_DIR, not a "reports/" sub-folder
    # that doesn't exist.  The reports are written to SCRIPT_DIR by
    # run_parallel.py (lines: report_dois_path = SCRIPT_DIR / "Relatório.txt").
    report_file = SCRIPT_DIR / "Relatório_artigos_por_nome.txt"
    failed_titles = _parse_failed_from_report(report_file)

    report_dois = SCRIPT_DIR / "Relatório.txt"
    failed_dois = _parse_failed_from_report(report_dois)

    items_to_search = failed_dois + failed_titles
    if not items_to_search:
        print("✅ Nenhum artigo pendente encontrado nos relatórios!")
        return

    print(
        f"🔍 Encontrados {len(items_to_search)} itens não resolvidos. "
        "Pesquisando nas bases complementares..."
    )

    found_count = 0
    for item in items_to_search:
        print(f"🔎 Pesquisando: {item[:60]}...")
        pmids = search_pubmed(item)
        if pmids:
            print(f"   🟢 Encontrado no PubMed! PMID: {pmids[0]}")
            found_count += 1
            time.sleep(1)
            continue

        ntrs_ids = search_ntrs(item)
        if ntrs_ids:
            print(f"   🟢 Encontrado no NASA NTRS! ID: {ntrs_ids[0]}")
            found_count += 1
            time.sleep(1)
            continue

        print(f"   🔴 Não encontrado nas bases complementares.")
        time.sleep(1)

    print("=" * 60)
    print(f"🏁 Busca Profunda Concluída! {found_count} novos identificadores descobertos.")
    print("=" * 60)


if __name__ == "__main__":
    run_deep_search()
