import {readFile} from 'node:fs/promises';import {stripTypeScriptTypes} from 'node:module';import assert from 'node:assert/strict';
const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');const module=async p=>stripTypeScriptTypes(await readFile(p,'utf8'));
const aiUrl=url(await module('lib/ai-analysis.ts')),domainUrl=url(await module('lib/domain.ts')),backupUrl=url((await module('lib/backup.ts')).replace("'./domain'",JSON.stringify(domainUrl)).replace("'./ai-analysis'",JSON.stringify(aiUrl)));
const report=await import(url((await module('lib/assessment-report.ts')).replace("'./ai-analysis'",JSON.stringify(aiUrl)).replace("'./backup'",JSON.stringify(backupUrl))));
let captured,name;globalThis.URL.createObjectURL=b=>{captured=b;return 'blob:test'};globalThis.document={createElement:()=>({set download(n){name=n},click(){}})};globalThis.setTimeout=()=>0;
const p={name:'Projeto <script>alert(1)</script>',state:{protocol:{version:1,population:'P',concept:'C',context:'C',inclusion:'I',exclusion:''},articles:[]}};
report.exportHTMLReport(p,'triagem',[]);const html=await captured.text();assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));assert.ok(html.includes('window.print()'));
await report.exportWordReport(p,'triagem',[]);assert.ok(name.endsWith('.docx'));const bytes=new Uint8Array(await captured.arrayBuffer()),entries={};let offset=0;while(new DataView(bytes.buffer).getUint32(offset,true)===0x04034b50){const v=new DataView(bytes.buffer,offset),size=v.getUint32(18,true),n=v.getUint16(26,true),extra=v.getUint16(28,true),entry=new TextDecoder().decode(bytes.slice(offset+30,offset+30+n)),start=offset+30+n+extra;entries[entry]=new TextDecoder().decode(bytes.slice(start,start+size));offset=start+size;}assert.ok(entries['[Content_Types].xml']);assert.ok(entries['_rels/.rels']);assert.ok(entries['word/document.xml'].includes('&lt;script&gt;'));
console.log('PASS: relatório HTML escapado, impressão e pacote DOCX com conteúdo OOXML.');
