import {validatePlanner,applyPlanner,newPlanner,type PlanStage} from '@/lib/protocol-planner';
import {incorporateWithPdf} from '@/lib/incorporate-pdf';
import {importAI,removeAI,stageName,analysesFor,isCurrent} from '@/lib/ai-analysis';
import {runAITriage} from '@/lib/ai-runner';
import {isMode,textKey,orphanTexts,ownKey} from '@/lib/motor-download';
import {pickProvider} from '@/lib/ai-provider';
import {restoredState} from '@/lib/validation';
import {identity,owned,database,bucket,body,ok,fail,commit,ApiError,requireRole} from '@/lib/server';
import {finalPcc,validateOpinion} from '@/lib/review';
import {requireProtocol,triageDecision,initialState} from '@/lib/domain';
export async function GET(r:Request,{params}:any){try{const actor=await identity(r),{id}=await params,p=await owned(id,actor);const docs=(await database().prepare("SELECT id,article,name,size,hash,status FROM documents WHERE project=? AND status='ready'").bind(id).all()).results;const searches=(await database().prepare('SELECT doi,status,result,error,updated FROM search_items WHERE project=? ORDER BY updated').bind(id).all()).results;const attempts=(await database().prepare('SELECT article,status,reason,created FROM pdf_attempts WHERE project=? ORDER BY created DESC LIMIT 2000').bind(id).all()).results;return ok({...p,attempts,state:JSON.parse(p.state),documents:docs,searches:searches.map((x:any)=>({...x,result:x.result?JSON.parse(x.result):null}))})}catch(e){return fail(e)}}
export async function PATCH(r:Request,{params}:any){try{const actor=await identity(r),{id}=await params,p=await owned(id,actor),b=await body(r);requireRole(p,['owner','editor','reviewer']);if(p.access_role==='reviewer'&&!['triage','fulltext','finalReview'].includes(b.action))throw new ApiError(403,'Revisores podem registrar apenas decisões de triagem e PCC.');if(b.revision!==p.revision)throw new ApiError(409,'Há alterações em outra aba. Atualize o projeto.');if(p.archived)throw new ApiError(409,'A exclusão deste projeto foi iniciada. Repita a exclusão para concluir.');const s=JSON.parse(p.state);if(s.importPending&&!['restore','finishImport','notes'].includes(b.action))throw new ApiError(409,'Conclua a importação antes de avaliar os registros.');
if(b.action==='protocol'){
 const q=b.protocol;if(!q||!Array.isArray(q.questions)||q.questions.length>30)throw new ApiError(400,'Protocolo inválido.');for(const k of ['population','concept','context','inclusion','exclusion'])if(typeof q[k]!=='string'||q[k].length>20000)throw new ApiError(400,'Campo inválido.');
 if(q.questions.some((x:any)=>typeof x!=='string'||!x.trim()||x.length>2000))throw new ApiError(400,'Pergunta inválida.');
 if(b.approve){try{requireProtocol(q)}catch(e:any){throw new ApiError(400,e.message)}}
 s.protocol={...q,approved:!!b.approve,version:s.protocol.version+1,approvedBy:b.approve?actor:null,approvedAt:b.approve?new Date().toISOString():null};
}else if(b.action==='planner'){
 try{s.planner=validatePlanner(b.planner)}catch(e:any){throw new ApiError(400,e.message)}
}else if(b.action==='plannerApply'){
 try{const stage=b.stage as PlanStage;if(!['pcc','triagem'].includes(stage))throw Error('Etapa inválida.');s.planner=validatePlanner(b.planner);s.protocol=applyPlanner(s.planner,stage,s.protocol);if(stage==='triagem')requireProtocol(s.protocol);s.protocol.approvedBy=stage==='triagem'?actor:null;s.protocol.approvedAt=stage==='triagem'?new Date().toISOString():null;s.planner.history.push({stage,event:'Aplicação aprovada',at:new Date().toISOString(),version:s.protocol.version,items:structuredClone(s.planner.stages[stage].items)});s.planner.history=s.planner.history.slice(-50)}catch(e:any){throw new ApiError(400,e.message)}
}else if(b.action==='incorporate'){
 return ok(await incorporateWithPdf(p,actor,s,String(b.doi||'')));
}else if(b.action==='localArticle'){
 if(typeof b.hash!=='string'||!/^([a-f0-9]{64})$/.test(b.hash)||typeof b.filename!=='string'||!b.filename.trim()||b.filename.length>250)throw new ApiError(400,'Arquivo local inválido.');
 const doc=await database().prepare("SELECT article FROM documents WHERE project=? AND hash=? AND status='ready'").bind(id,b.hash).first<any>();
 const existing=s.articles.find((a:any)=>a.id===doc?.article||a.source?.localHash===b.hash);
 if(existing)return ok({article:existing.id,existing:true,state:s,revision:p.revision});
 if(s.articles.length>=2000)throw new ApiError(400,'Limite de 2.000 registros por projeto nesta versão.');
 const article=crypto.randomUUID(),original=b.filename.replace(/[\\/\x00-\x1f]/g,'_');
 s.articles.push({id:article,doi:'',title:original.replace(/\.pdf$/i,''),authors:'',year:'',abstract:'',filename:article+'_'+original,source:{kind:'local',originalFilename:original,localHash:b.hash,importedAt:new Date().toISOString()}});
 return ok({...await commit(p,actor,s,b.action),article});
}else if(b.action==='runAI'){
 // Triagem automática. Produz o MESMO ORBIS_AI_RESULTS_V1 que a importação
 // manual consome, então segue pelo mesmo `importAI` e cai nas mesmas regras
 // de consenso, duplicata e divergência. Continua sendo rascunho: nenhuma
 // decisão humana é criada nem sobrescrita aqui (regra 2 do projeto).
 requireRole(p,['owner','editor']);
 const stage=stageName(b.stage)||'triagem';
 const provider=pickProvider(globalThis as any);
 if(!provider)throw new ApiError(400,'Nenhuma chave de provedor de IA está configurada neste ambiente. Use a importação manual.');
 let saida;try{saida=await runAITriage({...p,state:s},stage,provider,{batchSize:Number(b.batchSize)||undefined,readText:async(key:string)=>{if(!ownKey(id,key))return null;const o=await bucket().get(key);return o?await o.text():null}})}catch(e:any){throw new ApiError(502,e.message)}
 if(!saida.response)throw new ApiError(502,saida.failures[0]?.reason||'A IA não devolveu nenhuma avaliação.');
 let report;try{report=importAI(s,id,saida.response,stage,{})}catch(e:any){throw new ApiError(400,e.message)}
 return ok({...await commit(p,actor,s,'importAI'),aiReport:report,
  ai:{provider:provider.name,model:provider.model,analysed:saida.analysed,failures:saida.failures}});
}else if(b.action==='importAI'){
 const stage=stageName(b.stage);if(!stage)throw new ApiError(400,'Etapa de IA inválida.');let report;try{report=importAI(s,id,b.response,stage,b.mappings||{})}catch(e:any){throw new ApiError(400,e.message)}return ok({...await commit(p,actor,s,b.action),aiReport:report});
}else if(b.action==='removeAI'){
 let removed;try{removed=removeAI(s,b.selector||{})}catch(e:any){throw new ApiError(400,e.message)}if(!removed)throw new ApiError(404,'Análise não encontrada.');return ok({...await commit(p,actor,s,b.action),removed});
}else if(b.action==='clearStage'){
 requireRole(p,['owner','editor']);if(!['search','triagem','pcc','protocol'].includes(b.stage))throw new ApiError(400,'Etapa inválida.');
 if(b.stage==='search'){const db=database(),orphan=orphanTexts((await db.prepare('SELECT result FROM search_items WHERE project=?').bind(id).all()).results as any[],s.articles,id);for(let n=0;n<orphan.keys.length;n+=1000)await bucket().delete(orphan.keys.slice(n,n+1000));if(orphan.bytes)await db.prepare('UPDATE projects SET bytes=MAX(0,bytes-?) WHERE id=?').bind(orphan.bytes,id).run();await db.prepare('DELETE FROM search_items WHERE project=?').bind(id).run();return ok(await commit(p,actor,s,'clearSearch'));}
 if(b.stage==='protocol'){const version=s.protocol.version+1;s.protocol={...initialState().protocol,version};s.planner=newPlanner(s.protocol);for(const a of s.articles){delete a.triage;delete a.fulltext;delete a.finalReview;a.aiAnalyses=[];}return ok(await commit(p,actor,s,'clearProtocol'));}
 for(const a of s.articles){a.aiAnalyses=(a.aiAnalyses||[]).filter((x:any)=>b.stage==='triagem'?x.stage!=='triagem':x.stage!=='pcc');if(a.legacyDecision?.analisesIA)delete a.legacyDecision.analisesIA[b.stage];if(b.stage==='triagem')delete a.triage;delete a.fulltext;delete a.finalReview;}
}else if(b.action==='triage'){
 if(!s.protocol.approved)throw new ApiError(400,'Aprove o protocolo antes da triagem.');const a=s.articles.find((x:any)=>x.id===b.article);if(!a)throw new ApiError(404,'Artigo não encontrado.');if(!Array.isArray(b.answers)||b.answers.length!==s.protocol.questions.length)throw new ApiError(400,'Responda todas as perguntas.');let decision;try{decision=triageDecision(b.answers,String(b.reason||''))}catch(e:any){throw new ApiError(400,e.message)}a.triage={answers:b.answers,reason:String(b.reason||'').slice(0,20000),decision,actor,version:s.protocol.version};
}else if(b.action==='acceptAITriageBulk'){
 if(!s.protocol.approved)throw new ApiError(400,'Aprove o protocolo antes da triagem.');if(!Array.isArray(b.choices)||!b.choices.length||b.choices.length>500)throw new ApiError(400,'Selecione de 1 a 500 análises para aplicar.');const seen=new Set(),applied=[];for(const choice of b.choices){if(!choice||typeof choice.article!=='string'||typeof choice.analysis!=='string'||seen.has(choice.article))throw new ApiError(400,'Seleção de análises inválida ou repetida.');seen.add(choice.article);const a=s.articles.find((x:any)=>x.id===choice.article);if(!a)throw new ApiError(404,'Um artigo selecionado não foi encontrado.');if(a.triage?.version===s.protocol.version)throw new ApiError(409,'Um artigo selecionado já possui decisão humana na versão atual.');const analysis=analysesFor(a,'triagem').find((x:any)=>x.id===choice.analysis);if(!analysis||!isCurrent(analysis,a,s.protocol))throw new ApiError(409,'Uma análise selecionada está desatualizada ou não corresponde ao artigo.');if(!Array.isArray(analysis.questions)||analysis.questions.length!==s.protocol.questions.length)throw new ApiError(400,'Uma análise não respondeu todas as perguntas da triagem.');const answers=analysis.questions.map((q:any)=>q.answer==='sim'?'Sim':q.answer==='nao'?'Não':'Indeterminado'),reason=('Decisão aceita da análise '+analysis.provider+(analysis.model?' / '+analysis.model:'')+'. '+analysis.questions.map((q:any,i:number)=>(i+1)+'. '+q.reason+(q.evidence?' Evidência: '+q.evidence:'')).join(' ')).slice(0,20000);let decision;try{decision=triageDecision(answers,reason)}catch(e:any){throw new ApiError(400,e.message)}a.triage={answers,reason,decision,actor,version:s.protocol.version,source:'ia_accepted',analysisId:analysis.id,provider:analysis.provider,model:analysis.model,acceptedAt:new Date().toISOString()};delete a.fulltext;delete a.finalReview;applied.push({article:a.id,analysis:analysis.id,decision})}return ok({...await commit(p,actor,s,b.action),aiAccepted:{applied}});
}else if(b.action==='abstract'){
 const a=s.articles.find((x:any)=>x.id===b.article);if(!a)throw new ApiError(404,'Artigo não encontrado.');a.abstract=String(b.abstract||'').slice(0,50000);if(a.triage)a.triage.version=-1;
}else if(b.action==='fulltext'){
 if(!s.protocol.approved)throw new ApiError(400,'Aprove o protocolo primeiro.');const a=s.articles.find((x:any)=>x.id===b.article);if(!a||a.triage?.version!==s.protocol.version||a.triage?.decision!=='incluir')throw new ApiError(400,'Conclua a triagem na versão atual.');
 if(!await database().prepare("SELECT id FROM documents WHERE project=? AND article=? AND status='ready'").bind(id,a.id).first())throw new ApiError(400,'Anexe e confira o PDF antes de registrar a avaliação integral.');
 if(!['r1','r2','adjudication'].includes(b.slot))throw new ApiError(400,'Parecer inválido.');let v;try{v=validateOpinion(b.opinion,s.protocol.version,actor)}catch(e:any){throw new ApiError(400,e.message)}a.fulltext=a.fulltext||{};
 if(b.slot==='adjudication'){if(finalPcc(a,s.protocol.version).status!=='conflito')throw new ApiError(400,'Não existe conflito atual para adjudicar.');if(v.decision==='duvida')throw new ApiError(400,'A adjudicação deve resolver o conflito.');if([a.fulltext.r1?.reviewer,a.fulltext.r2?.reviewer].some(x=>x?.toLowerCase()===v.reviewer.toLowerCase()))throw new ApiError(400,'Identifique um terceiro revisor para adjudicar.');}
 else{const other=a.fulltext[b.slot==='r1'?'r2':'r1'];if(other?.reviewer.toLowerCase()===v.reviewer.toLowerCase())throw new ApiError(400,'Os dois pareceres devem pertencer a pessoas diferentes.');delete a.fulltext.adjudication;}
 a.fulltext[b.slot]=v;delete a.finalReview;
}else if(b.action==='finalReview'){
 const a=s.articles.find((x:any)=>x.id===b.article);if(!a||a.triage?.version!==s.protocol.version||finalPcc(a,s.protocol.version).decision!=='incluir')throw new ApiError(400,'O artigo precisa estar incluído no PCC atual.');if(!['incluir','excluir'].includes(b.decision)||!String(b.reason||'').trim())throw new ApiError(400,'Selecione a decisão e registre a justificativa.');a.finalReview={decision:b.decision,reason:String(b.reason).slice(0,20000),version:s.protocol.version,actor,at:new Date().toISOString()};
}else if(b.action==='removeArticle'){
 requireRole(p,['owner','editor']);const index=s.articles.findIndex((x:any)=>x.id===b.article);if(index<0)throw new ApiError(404,'Artigo não encontrado no corpus.');const article=s.articles[index];if(b.confirmation!==article.id)throw new ApiError(409,'Confirme novamente a exclusão deste artigo.');const db=database(),docs=(await db.prepare('SELECT id,key,size FROM documents WHERE project=? AND article=?').bind(id,article.id).all()).results as any[],ownText=ownKey(id,article.texto?.key),released=docs.reduce((sum:number,d:any)=>sum+Number(d.size||0),0)+(ownText?Number(article.texto.bytes||0):0),keys=[...docs.map((d:any)=>d.key),...(ownText?[article.texto.key]:[])];if(keys.length)await bucket().delete(keys);s.articles.splice(index,1);const at=new Date().toISOString(),snapshot=JSON.stringify(s),audit=JSON.stringify({removedArticle:{id:article.id,title:article.title,doi:article.doi,filename:article.filename}});const results=await db.batch([db.prepare('INSERT INTO events(id,project,actor,action,revision,created,snapshot) SELECT ?,id,?,?,revision+1,?,? FROM projects WHERE id=? AND revision=?').bind(crypto.randomUUID(),actor,'removeArticle',at,audit,id,p.revision),db.prepare('UPDATE projects SET state=?,bytes=MAX(0,bytes-?),revision=revision+1,updated=? WHERE id=? AND revision=?').bind(snapshot,released,at,id,p.revision),db.prepare('DELETE FROM documents WHERE project=? AND article=?').bind(id,article.id),db.prepare('DELETE FROM pdf_attempts WHERE project=? AND article=?').bind(id,article.id),db.prepare("UPDATE search_items SET result=json_remove(result,'$.motor') WHERE project=? AND doi=? AND result IS NOT NULL").bind(id,article.doi||'')]);if(!results[1].meta.changes)throw new ApiError(409,'O projeto mudou em outra aba. Atualize antes de excluir.');return ok({revision:p.revision+1,state:s,updated:at,removed:article.id,released});
}else if(b.action==='downloadMode'){
 requireRole(p,['owner','editor']);if(!isMode(b.mode))throw new ApiError(400,'Modo de download inválido.');s.settings={...s.settings,downloadMode:b.mode};
}else if(b.action==='notes'){s.notes=String(b.notes||'').slice(0,100000);
}else if(b.action==='restore'){
 if(s.articles.length||s.protocol.version)throw new ApiError(400,'Importe somente em um projeto novo.');const parsed=restoredState.safeParse(b.state);if(!parsed.success)throw new ApiError(400,'O backup contém campos incompatíveis. O projeto original foi preservado.');const v=parsed.data;if(!v||!Array.isArray(v.articles)||v.articles.length>2000||!v.protocol)throw new ApiError(400,'Backup inválido.');const ids=new Set();for(const a of v.articles){if(typeof a.id!=='string'||ids.has(a.id)||typeof a.title!=='string')throw new ApiError(400,'Registros inválidos no backup.');ids.add(a.id);}const names=new Set();for(const a of v.articles){if(typeof a.filename!=='string'||!a.filename||names.has(a.filename))throw new ApiError(400,'Nomes de artigos duplicados ou ausentes.');names.add(a.filename);}Object.assign(s,initialState(),v,{importPending:true,importHash:String(b.hash||''),importExpected:Array.isArray(b.expected)?b.expected:[]});for(const a of s.articles)if(a.texto?.key)a.texto={...a.texto,key:await textKey(id,a.doi||a.id)};
 if(Array.isArray(b.searches)){if(b.searches.length>2000)throw new ApiError(400,'Lote importado muito grande.');for(let n=0;n<b.searches.length;n+=50)await database().batch(b.searches.slice(n,n+50).filter((x:any)=>/^10\.\d{4,9}\/\S+$/i.test(x.doi)).map((x:any)=>database().prepare('INSERT INTO search_items(project,doi,status,result,error,updated) VALUES(?,?,?,?,?,?) ON CONFLICT(project,doi) DO NOTHING').bind(id,x.doi,x.status==='done'?'done':'waiting',x.result?JSON.stringify({...x.result,motor:undefined}):null,x.error||null,new Date().toISOString())));}

}else if(b.action==='finishImport'){
 const ready=(await database().prepare("SELECT name FROM documents WHERE project=? AND status='ready'").bind(id).all()).results as any[];
 if((s.importExpected||[]).some((name:string)=>!ready.some(d=>d.name===name)))throw new ApiError(409,'Ainda faltam PDFs da importação. Selecione novamente o backup para retomar.');s.importPending=false;

}else throw new ApiError(400,'Operação desconhecida.');
return ok(await commit(p,actor,s,b.action));}catch(e){return fail(e)}}
export async function DELETE(r:Request,{params}:any){try{const actor=await identity(r),{id}=await params,p=await owned(id,actor),b=await body(r);requireRole(p,['owner']);if(b.confirmation!==p.name||b.revision!==p.revision)throw new ApiError(409,'Confirme o nome e a versão atual do projeto antes de excluir.');const db=database();await db.prepare('UPDATE projects SET archived=1 WHERE id=? AND owner=?').bind(id,actor).run();const {bucket}=await import('@/lib/server');while(true){const objects=await bucket().list({prefix:id+'/',limit:1000});if(!objects.objects.length)break;await bucket().delete(objects.objects.map(o=>o.key));}await db.batch(['pdf_attempts','documents','events','search_items','project_members'].map(table=>db.prepare('DELETE FROM '+table+' WHERE project=?').bind(id)).concat([db.prepare('DELETE FROM projects WHERE id=? AND owner=?').bind(id,actor)]));return ok({deleted:true})}catch(e){return fail(e)}}
