'use client';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {analysesFor,makeAIPackage,parseAI,normalizeAIResponse,isCurrent,displayTitle,stageName,type AIStage} from '@/lib/ai-analysis';
import {download,zip} from '@/lib/backup';import {exportHTMLReport,exportWordReport,exportAnalysisCSV} from '@/lib/assessment-report';
function pccInstruction(pkg:any){return `TAREFA OBRIGATÓRIA — ANÁLISE PCC DO ORBIS

Leia pedido_IA.json e todos os PDFs da pasta pdfs. Avalie cada artigo pelo texto completo usando exatamente os critérios de inclusão e exclusão do pedido.

Não responda com resumo em texto. Retorne SOMENTE um objeto JSON válido, sem introdução e sem bloco Markdown, copiando schema, project_id, etapa, package_id, criteria_hash e corpus_id do formato_resposta. Para cada artigo, copie article_id, arquivo e source_hash e preencha todos os itens de inclusao e exclusao com atende (true, false ou null), motivo, evidencia e pagina.

Não use etapa "triagem" nem triagem_nivel1. A etapa obrigatória é "pcc". A resposta deve conter exatamente ${pkg.items.length} artigos. Se um PDF estiver ilegível, use null nos critérios afetados e explique o motivo. Nome sugerido: ORBIS_resposta_PCC.json.`}
export function AIRemove({selector,label,busy,save}:any){const [open,setOpen]=useState(false);return <><Button variant="outline" disabled={busy} onClick={()=>setOpen(true)}>{label}</Button><AlertDialog open={open} onOpenChange={setOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{label}?</AlertDialogTitle><AlertDialogDescription>As análises selecionadas serão retiradas da comparação ativa. As decisões humanas, os PDFs e as outras IAs serão preservados. A alteração ficará no histórico do projeto.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><Button disabled={busy} variant="destructive" onClick={async()=>{if(await save('removeAI',{selector}))setOpen(false)}}>Confirmar exclusão</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></>}
export default function AIControls({project,stage,busy,save}:any){const ref=useRef<HTMLInputElement>(null),[text,setText]=useState(''),[payload,setPayload]=useState<any>(null),[mappings,setMappings]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[preparing,setPreparing]=useState(false),[reading,setReading]=useState(false),[rodandoIA,setRodandoIA]=useState(false);
 // Triagem automática. Produz o mesmo ORBIS_AI_RESULTS_V1 da importação
 // manual, então entra pela mesma porta e vira rascunho — nunca decisão.
 async function analisarComIA(){
  if(busy||rodandoIA)return;
  setRodandoIA(true);
  try{
   const r:any=await save('runAI',{stage});
   const falhas=r?.ai?.failures?.length;
   setMessage('Análise concluída por '+(r?.ai?.provider||'IA')+' ('+(r?.ai?.analysed||0)+' artigo(s)).'
    +(falhas?' '+falhas+' lote(s) falharam e continuam pendentes.':'')
    +' Os pareceres entraram como rascunho: aplique-os quando concordar.');
  }catch(e:any){setMessage(e?.message||'Não foi possível executar a análise automática.');}
  finally{setRodandoIA(false);}
 }
 const report=[...(project.state.aiImports||[])].reverse().find((x:any)=>x.stage===stage),runs=new Map<string,any>(),providers=new Map<string,any>();
 for(const a of project.state.articles)for(const x of analysesFor(a,stage)){const r=runs.get(x.runId)||{...x,count:0};r.count++;runs.set(x.runId,r);providers.set(x.provider+'::'+x.model,{provider:x.provider,model:x.model})}
 async function read(value:string){setReading(true);try{let obj=parseAI(value);if(obj.schema==='ORBIS_WEB_MANUAL_RESPONSE_V1'&&typeof obj.proposal==='string'){try{obj=parseAI(obj.proposal)}catch{throw Error('Esta resposta contém apenas proposta textual. Exporte o pacote de análise PCC para receber avaliações por artigo.')}}if(obj?.schema==='ORBIS_PROTOCOL_RESPONSE_V1')throw Error('Este JSON é uma resposta do planejamento. Use “Ler resposta do planejamento JSON” na construção do PCC ou da triagem.');if(obj?.schema==='ORBIS_AI_PACKAGE_MD_V1'||obj?.schema==='ORBIS_PROTOCOL_REQUEST_V1')throw Error('Este arquivo é um pedido enviado à IA. Importe o arquivo de resposta produzido pela IA.');const fileStage=stageName(obj?.etapa??obj?.stage) || stageName(obj?.items?.[0]?.etapa);obj=normalizeAIResponse(obj,fileStage||stage);if(!Array.isArray(obj.items))throw Error('JSON sem uma lista de artigos (items). Confira o formato de resposta do pacote PCC.');const targetStage=fileStage||stage;setMappings({});setMessage('Lendo '+obj.items.length+' avaliações…');let revision=project.revision,applied=0,skipped=0,duplicates=0;for(let index=0;index<obj.items.length;index+=30){const batch={...obj,items:obj.items.slice(index,index+30)};setPayload(batch);const result=await save('importAI',{stage:targetStage,response:batch,_revision:revision});if(!result)throw Error('Importação interrompida no lote '+(Math.floor(index/30)+1)+'. As avaliações anteriores já foram salvas; importe novamente para continuar.');revision=result.revision;applied+=result.aiReport?.applied||0;skipped+=result.aiReport?.skipped?.length||0;duplicates+=result.aiReport?.duplicates||0}setMessage((targetStage!==stage?'Arquivo identificado como '+(targetStage==='triagem'?'triagem':'PCC')+' e registrado na etapa correta. ':'')+applied+' avaliações incluídas; '+skipped+' pendentes; '+duplicates+' repetidas. '+(targetStage!==stage?'Abra a etapa correspondente para ver a tabela e o relatório.':'Confira a tabela e o relatório.'))}catch(e:any){setMessage(e.message)}finally{setReading(false)}}
 async function exportPackage(){setPreparing(true);setMessage('');try{const pkg=makeAIPackage(project,stage);if(!pkg.items.length)throw Error('Não há artigos elegíveis para exportar nesta etapa.');if(stage==='triagem'){download(new Blob([JSON.stringify(pkg,null,2)],{type:'application/json'}),'ORBIS_triagem_IA.json')}else{const files:{name:string;blob:Blob}[]=[],missing:string[]=[];for(const item of pkg.items){const doc=project.documents.find((d:any)=>d.article===item.article_id);if(!doc){const a=project.state.articles.find((x:any)=>x.id===item.article_id);if(a?.texto?.key){const t=await fetch('/api/projects/'+project.id+'/texto?article='+encodeURIComponent(a.id));if(t.ok){files.push({name:'textos/'+item.arquivo.replace(/[\\/]/g,'_')+'.txt',blob:await t.blob()});continue}}missing.push(item.arquivo);continue}const r=await fetch('/api/projects/'+project.id+'/pdf?document='+doc.id);if(!r.ok)throw Error('Não foi possível obter '+item.arquivo);files.push({name:'pdfs/'+item.arquivo.replace(/[\\/]/g,'_'),blob:await r.blob()})}const instruction=pccInstruction(pkg);files.push({name:'00_INSTRUCAO_OBRIGATORIA_PCC.txt',blob:new Blob([instruction])},{name:'pedido_IA.json',blob:new Blob([JSON.stringify(pkg,null,2)])},{name:'modelo_da_resposta.json',blob:new Blob([JSON.stringify(pkg.formato_resposta,null,2)])},{name:'LEIA-ME.txt',blob:new Blob([instruction+'\n\nPDFs ausentes do pacote: '+(missing.join('\n')||'nenhum')])});download(await zip(files),'ORBIS_PCC_IA_e_PDFs.zip')}
 setMessage(stage==='pcc'?'Pacote preparado. No Gemini, envie o ZIP e use “Copiar instrução para o Gemini”. Depois importe somente o JSON de resposta.':'Pacote preparado. Envie-o à IA de sua escolha e importe o JSON de resposta.');}catch(e:any){setMessage(e.message)}finally{setPreparing(false)}}
 return <section className="panel ai-controls"><h2>Análises de IA</h2><p>Importe uma ou várias análises por artigo. Os resultados preenchem a coluna de IA e a ficha; a decisão humana continua independente.</p><div className="actions"><Button disabled={busy||preparing||reading} variant="outline" onClick={exportPackage}>{preparing?'Preparando…':stage==='pcc'?'Exportar pacote PCC com PDFs':'Exportar artigos para IA'}</Button><Button disabled={busy||rodandoIA||preparing||reading} onClick={analisarComIA}>{rodandoIA?'Analisando…':'Analisar com IA'}</Button><Button disabled={busy||preparing||reading} onClick={()=>ref.current?.click()}>{reading?'Lendo respostas…':'Ler resposta JSON e atualizar tabela'}</Button><Button variant="outline" onClick={()=>exportAnalysisCSV(project,stage)}>Exportar análises CSV</Button><Button variant="outline" onClick={()=>exportHTMLReport(project,stage,project.state.articles)}>Relatório / imprimir PDF</Button><Button variant="outline" onClick={()=>exportWordReport(project,stage,project.state.articles).catch(e=>setMessage(e.message))}>Relatório Word</Button></div><input ref={ref} type="file" accept=".json,application/json" hidden onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(f){if(f.size>10*1024*1024){setMessage('Arquivo acima de 10 MB. Divida a resposta em arquivos menores.');return}await read(await f.text())}}}/>
 <details><summary>Colar resposta da IA</summary><Textarea aria-label="Resposta JSON da IA" rows={7} value={text} onChange={e=>setText(e.target.value)} placeholder="Cole o JSON ORBIS_AI_RESULTS_V1, inclusive se vier em um bloco de código."/><Button disabled={busy||reading||!text.trim()} onClick={()=>read(text)}>Ler resposta colada e atualizar tabela</Button></details>{message&&<p role="status">{message}</p>}
 {report&&<details open={!!report.skipped.length}><summary>Última importação: {report.applied} aplicados · {report.duplicates} já existentes · {report.skipped.length} pendentes</summary><p>{report.provider} / {report.model||'modelo não informado'} · {new Date(report.at).toLocaleString('pt-BR')}</p>{report.skipped.map((row:any)=><div className="ai-match" key={row.index}><strong>{row.file}</strong><p>{row.reason}</p>{payload&&<Select value={mappings[row.index]||''} onValueChange={v=>setMappings({...mappings,[row.index]:v})}><SelectTrigger aria-label={'Associar '+row.file}><SelectValue placeholder="Associar ao artigo correto"/></SelectTrigger><SelectContent>{project.state.articles.map((a:any)=><SelectItem key={a.id} value={a.id}>{displayTitle(a)}</SelectItem>)}</SelectContent></Select>}</div>)}{payload&&report.skipped.length>0&&<Button disabled={busy} onClick={async()=>{if(await save('importAI',{stage,response:payload,mappings}))setMessage('Associações processadas. Confira o relatório atualizado.')}}>Tentar novamente com as associações</Button>}<Button variant="outline" onClick={()=>download(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),'ORBIS_relatorio_importacao_IA.json')}>Baixar relatório de importação</Button><details><summary>Conferir correspondências de artigos</summary>{report.matches.map((m:any)=><p key={m.index}>{m.file} — {m.method}</p>)}</details></details>}
 <details><summary>Gerenciar análises importadas ({runs.size} execuções)</summary>{!runs.size&&<p>Nenhuma análise importada nesta etapa.</p>}{[...runs.values()].map(r=><div className="ai-run-row" key={r.runId}><div><strong>{r.provider} / {r.model||'modelo não informado'}</strong><small>{r.count} artigos · {new Date(r.importedAt).toLocaleString('pt-BR')}</small></div><AIRemove label="Excluir execução" selector={{scope:'run',runId:r.runId}} busy={busy} save={save}/></div>)}{[...providers.values()].map(p=><div className="ai-run-row" key={p.provider+p.model}><span>{p.provider} / {p.model||'modelo não informado'} · todas as etapas</span><AIRemove label="Excluir todas as análises desta IA" selector={{scope:'provider',...p}} busy={busy} save={save}/></div>)}</details></section>
}
export function AIArticleDetails({project,article,stage,busy,save}:any){const list=analysesFor(article,stage);return <section className="panel ai-article-details"><h2>Análises e evidências das IAs</h2><div className="actions"><Button variant="outline" onClick={()=>exportHTMLReport(project,stage,[article])}>Ficha / imprimir PDF</Button><Button variant="outline" onClick={()=>exportWordReport(project,stage,[article])}>Ficha Word</Button></div>{!list.length&&<p>Nenhuma análise de IA importada para este artigo nesta etapa.</p>}{list.map(x=><article className="ai-analysis-card" key={x.id}><header><h3>{x.provider} / {x.model||'modelo não informado'}</h3><span className={'assessment-status status-'+x.decision}>Sugestão: {x.decision==='incluir'?'Manter':x.decision==='excluir'?'Excluir':'Indeterminado'}</span></header><small>{new Date(x.importedAt).toLocaleString('pt-BR')} · Protocolo v{x.protocolVersion}</small>{!isCurrent(x,article,project.state.protocol)&&<p className="notice">{x.warning||'Protocolo ou referência alterados. Análise histórica, fora da concordância atual.'}</p>}{x.title&&<p><strong>Título informado pela IA:</strong> {x.title}</p>}{x.authors&&<p><strong>Autores informados pela IA:</strong> {x.authors}</p>}<h4>Resumo desta IA</h4><p className="ai-summary">{x.summary||'Não informado.'}</p>{x.duplicate&&<p className="notice">Possível duplicata indicada pela IA: {x.duplicateOf||'sem referência'} — {x.duplicateReason}. Confira antes de decidir.</p>}{[['Perguntas da triagem',x.questions],['Critérios de inclusão',x.inclusion],['Critérios de exclusão',x.exclusion]].map(([title,rows]:any)=>rows.length>0&&<section key={title}><h4>{title}</h4>{rows.map((q:any)=><div className="ai-criterion" key={q.index}><strong>{q.index}. {q.text}</strong><span className={'assessment-status '+(q.answer==='sim'?'status-incluir':q.answer==='nao'?'status-excluir':'status-pending')}>{q.answer==='sim'?'Sim':q.answer==='nao'?'Não':'Indeterminado'}</span><p>{q.reason}</p>{q.evidence&&<blockquote>{q.evidence}{q.page?' — página '+q.page:''}</blockquote>}</div>)}</section>)}<details><summary>Rastreabilidade da análise</summary><p>Execução: {x.runId}</p><p>Pacote: {x.packageId||'não informado'}</p><p>Critérios: {x.criteriaHash||'não informado'}</p></details><AIRemove label="Excluir esta análise do artigo" selector={{scope:'article',article:article.id,analysis:x.id}} busy={busy} save={save}/></article>)}</section>}
