'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import {AlertDialog,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from '@/components/ui/alert-dialog';
import {finalPcc} from '@/lib/review';
import ReviewPanel from './review-panel';
import AIControls,{AIArticleDetails} from './ai-controls';
import {aiConsensus,analysesFor,displayTitle} from '@/lib/ai-analysis';
import ClearStageButton from './clear-stage-button';
const verdict=(v:string)=>({incluir:'Incluir',excluir:'Excluir',duvida:'Indeterminado'}[v]||'Pendente');
export default function AssessmentWorkspace({project,busy,save,clearStage,pcc=false}:any){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('number'),[page,setPage]=useState(1),[selected,setSelected]=useState(''),[dirty,setDirty]=useState(false),[aiFilter,setAiFilter]=useState('all'),[bulkOpen,setBulkOpen]=useState(false),[conflictChoices,setConflictChoices]=useState<Record<string,string>>({});
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 const aiStage=pcc?'pcc':'triagem';
 const protocol=project.state.protocol,version=protocol.version;
 const articles=project.state.articles.filter((a:any)=>!pcc||(a.triage?.version===version&&a.triage.decision==='incluir'));
 function status(a:any){if(pcc){const x=finalPcc(a,version);return x.status==='conflito'?'conflict':x.decision||'pending'}return a.triage?.version===version?a.triage.decision:'pending'}
 const totals={all:articles.length,pending:articles.filter((a:any)=>status(a)==='pending').length,incluir:articles.filter((a:any)=>status(a)==='incluir').length,excluir:articles.filter((a:any)=>status(a)==='excluir').length,conflict:articles.filter((a:any)=>status(a)==='conflict').length};
 const labels:any={all:'Todos',pending:pcc?'Aguardando pareceres':'Em análise',incluir:pcc?'Incluídos':'Mantidos',excluir:'Excluídos',conflict:'Conflitos'};
 const filtered=articles.filter((a:any)=>(filter==='all'||status(a)===filter)&&[displayTitle(a),a.title,a.authors,a.doi,a.filename].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(aiFilter==='all'||aiConsensus(a,aiStage,protocol).status===aiFilter)).sort((a:any,b:any)=>sort==='title'?displayTitle(a).localeCompare(displayTitle(b),'pt-BR'):sort==='author'?(a.authors||'').localeCompare(b.authors||'','pt-BR'):0);
 const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages),visible=filtered.slice((current-1)*10,current*10);
 const article=articles.find((a:any)=>a.id===selected),index=filtered.findIndex((a:any)=>a.id===selected);
 const locked=busy||dirty;
 const pendingAI=articles.filter((a:any)=>status(a)==='pending').map((a:any)=>({article:a,consensus:aiConsensus(a,aiStage,protocol)}));
 const automaticAI=!pcc?pendingAI.filter((x:any)=>['single','agreement'].includes(x.consensus.status)&&x.consensus.current.length):[];
 const conflictingAI=!pcc?pendingAI.filter((x:any)=>x.consensus.status==='conflict'&&x.consensus.current.length>1):[];
 function changePage(next:number){if(dirty&&!window.confirm('Há alterações não salvas na ficha atual. Descartar e mudar de página?'))return;if(dirty)setDirty(false);setSelected('');setPage(Math.max(1,Math.min(pages,next)));requestAnimationFrame(()=>document.querySelector('.assessment-list')?.scrollIntoView({behavior:'smooth',block:'start'}))}
 async function acceptAIInBulk(){const choices=[...automaticAI.map((x:any)=>({article:x.article.id,analysis:x.consensus.current[0].id})),...conflictingAI.filter((x:any)=>conflictChoices[x.article.id]).map((x:any)=>({article:x.article.id,analysis:conflictChoices[x.article.id]}))];if(!choices.length)return;const result=await save('acceptAITriageBulk',{choices});if(result){setBulkOpen(false);setConflictChoices({})}}
 return <div className="assessment"><div className="stats assessment-stats">{(['all','pending','incluir','excluir',...(pcc?['conflict']:[])] as (keyof typeof totals)[]).map(k=><div key={k} className={'metric-'+k}><strong>{totals[k]}</strong><span>{labels[k]}</span></div>)}</div>
 <section className="assessment-guide"><div className="section-top"><strong>{pcc?'Texto completo · Análise PCC':'Nível 1 · Título e resumo'}</strong><ClearStageButton stage={pcc?'pcc':'triagem'} label={pcc?'Limpar análise PCC':'Limpar triagem'} disabled={busy||!['owner','editor'].includes(project.access_role)} onClear={clearStage} description={pcc?'Remove pareceres R1 e R2, adjudicações, decisões finais e análises de IA do PCC. A triagem e o corpus serão preservados.':'Remove decisões e análises de IA da triagem. Pareceres PCC e decisões finais também serão removidos para manter a sequência metodológica. O corpus e os PDFs serão preservados.'}/></div><p>{pcc?'Confira o PDF e os critérios. Registre R1 e R2; quando houver divergência, registre a adjudicação.':'Leia o título e o resumo, responda às perguntas e registre a decisão. Um “Não” justificado exclui; “Indeterminado” mantém o artigo para leitura completa.'}</p><Progress value={totals.all?100*(totals.incluir+totals.excluir)/totals.all:0}/><small>{totals.incluir+totals.excluir} de {totals.all} avaliações concluídas no protocolo v{version}</small></section>
 <AIControls project={project} stage={aiStage} busy={locked} save={save}/>
 {!pcc&&<section className="panel ai-bulk-panel"><div><h2>Aplicar análises da IA à triagem</h2><p>O ORBIS pode preencher somente os artigos ainda pendentes. Concordâncias são agrupadas; nas divergências, você escolhe qual IA seguir.</p></div><div className="actions"><span><strong>{automaticAI.length}</strong> concordantes ou com uma IA</span><span><strong>{conflictingAI.length}</strong> divergentes</span><Button disabled={locked||(!automaticAI.length&&!conflictingAI.length)} onClick={()=>setBulkOpen(true)}>Concordar com análises da IA…</Button></div></section>}
 <section className="panel assessment-list"><div className="assessment-controls"><Input aria-label="Buscar artigos nesta etapa" placeholder="Buscar título, autor, DOI ou arquivo…" value={query} disabled={locked} onChange={e=>{setQuery(e.target.value);setPage(1)}}/><Select value={sort} disabled={locked} onValueChange={v=>{setSort(v);setPage(1)}}><SelectTrigger aria-label="Ordenar artigos"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="number">Ordem de entrada</SelectItem><SelectItem value="title">Título</SelectItem><SelectItem value="author">Autor</SelectItem></SelectContent></Select><Select value={aiFilter} disabled={locked} onValueChange={v=>{setAiFilter(v);setPage(1)}}><SelectTrigger aria-label="Filtrar análises de IA"><SelectValue/></SelectTrigger><SelectContent>{[['all','Todas as análises IA'],['none','Sem análise IA'],['single','Uma análise IA'],['agreement','Concordância IA'],['conflict','Divergência IA'],['stale','Conferir contexto IA']].map(([v,label])=><SelectItem key={v} value={v}>{label}</SelectItem>)}</SelectContent></Select></div>
 <Tabs value={filter} onValueChange={v=>{setFilter(v);setPage(1)}}><TabsList className="assessment-tabs">{Object.keys(labels).filter(k=>pcc||k!=='conflict').map(k=><TabsTrigger disabled={locked} key={k} value={k}>{labels[k]} ({totals[k as keyof typeof totals]})</TabsTrigger>)}</TabsList></Tabs>
 <Table><TableHeader><TableRow><TableHead>Artigo / autor</TableHead>{pcc&&<><TableHead>Revisor 1</TableHead><TableHead>Revisor 2</TableHead></>}<TableHead>Análises de IA</TableHead><TableHead>{pcc?'Decisão humana / consenso':'Decisão humana'}</TableHead><TableHead>PDF</TableHead><TableHead>Ficha</TableHead></TableRow></TableHeader><TableBody>{visible.map((a:any)=><TableRow key={a.id} data-state={selected===a.id?'selected':undefined}><TableCell><strong>{displayTitle(a)}</strong>{displayTitle(a)!==a.title&&<small>Título identificado pela IA · confira na ficha</small>}<small>{a.authors||'Autor não informado'}{a.year?' · '+a.year:''}</small><small>{a.doi||'Sem DOI'}</small></TableCell>{pcc&&['r1','r2'].map(slot=><TableCell key={slot}>{a.fulltext?.[slot]?.version===version?<><span>{verdict(a.fulltext[slot].decision)}</span><small>{a.fulltext[slot].reviewer}</small></>:'Pendente'}</TableCell>)}<TableCell>{(()=>{const c=aiConsensus(a,aiStage,protocol);return <><strong>{c.label}</strong>{c.runs.map(x=><div className="ai-table-run" key={x.id}><small>{x.provider} / {x.model||'modelo não informado'}</small><span className={'assessment-status status-'+x.decision}>{x.decision==='incluir'?'Manter':x.decision==='excluir'?'Excluir':'Indeterminado'}</span></div>)}</>})()}</TableCell><TableCell><span className={'assessment-status status-'+status(a)}>{labels[status(a)]}</span>{pcc&&<small>{finalPcc(a,version).status}</small>}{!pcc&&a.triage&&a.triage.version!==version&&<small>Reavaliar: protocolo ou resumo alterado</small>}</TableCell><TableCell>{project.documents.some((d:any)=>d.article===a.id)?'Disponível':'Pendente'}</TableCell><TableCell><Button variant="outline" disabled={locked} onClick={()=>{setSelected(a.id);requestAnimationFrame(()=>document.getElementById('assessment-detail')?.scrollIntoView({behavior:'smooth',block:'start'}))}}>{selected===a.id?'Em visualização':'Abrir ficha'}</Button></TableCell></TableRow>)}</TableBody></Table>
 {!filtered.length&&<p className="assessment-empty">{articles.length?'Nenhum artigo corresponde aos filtros.':pcc?'Os artigos mantidos na triagem aparecerão aqui.':'Importe artigos no corpus para começar a triagem.'}</p>}
 <div className="assessment-pagination"><span>{filtered.length} artigos · Página {current} de {pages}</span><div><Button type="button" variant="outline" disabled={busy||current<=1} onClick={()=>changePage(current-1)}>Anterior</Button><Select value={String(current)} disabled={busy||pages<=1} onValueChange={v=>changePage(Number(v))}><SelectTrigger aria-label="Escolher página"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:pages},(_,i)=><SelectItem key={i+1} value={String(i+1)}>Página {i+1}</SelectItem>)}</SelectContent></Select><Button type="button" variant="outline" disabled={busy||current>=pages} onClick={()=>changePage(current+1)}>Próxima</Button></div></div></section>
 {article?<section id="assessment-detail" className="assessment-detail"><div className="section-top"><div><p className="eyebrow">FICHA DO ARTIGO</p><h2>{displayTitle(article)}</h2></div><div className="actions"><Button variant="outline" disabled={locked||index<=0} onClick={()=>setSelected(filtered[index-1].id)}>Anterior</Button><Button variant="outline" disabled={locked||index<0||index>=filtered.length-1} onClick={()=>setSelected(filtered[index+1].id)}>Próximo</Button><Button variant="ghost" disabled={locked} onClick={()=>setSelected('')}>Fechar ficha</Button></div></div>
 <div className="assessment-columns"><aside><section className="panel"><h3>Referência e leitura</h3><p><strong>Título original:</strong> {article.title}</p><p>{article.authors||'Autor não informado'} {article.year}</p>{article.doi&&<p><a className="text-link" href={'https://doi.org/'+article.doi} target="_blank" rel="noopener noreferrer">{article.doi}</a></p>}<div className="actions">{project.documents.filter((d:any)=>d.article===article.id).map((d:any)=><a className="text-link" key={d.id} href={'/api/projects/'+project.id+'/pdf?document='+d.id}>Baixar PDF</a>)}</div><h3>Resumo original</h3><div className="assessment-abstract">{article.abstract||'Resumo não disponível. Complemente no corpus; não presuma ausência de evidência como exclusão.'}</div></section><section className="panel"><h3>Protocolo de referência · v{version}</h3>{[['População',protocol.population],['Conceito',protocol.concept],['Contexto',protocol.context],['Inclusão',protocol.inclusion],['Exclusão',protocol.exclusion]].map(([label,value])=><div className="criterion-reference" key={label}><strong>{label}</strong><p>{value||'Não informado'}</p></div>)}</section></aside>
 <div>{pcc?<ReviewPanel key={article.id} project={{...project,state:{...project.state,articles:[article]}}} busy={busy} save={save}/>:<TriageForm key={article.id+':'+version+':'+(article.triage?.version??'')} article={article} protocol={protocol} guidance={project.state.planner?.stages?.triagem?.items||[]} busy={busy} save={save} onDirty={setDirty}/>}</div></div><AIArticleDetails project={project} article={article} stage={aiStage} busy={locked} save={save}/></section>:<div className="notice">Selecione “Abrir ficha” para visualizar o resumo, os critérios e a avaliação do artigo.</div>}
 {!pcc&&<AlertDialog open={bulkOpen} onOpenChange={setBulkOpen}><AlertDialogContent className="ai-bulk-dialog"><AlertDialogHeader><AlertDialogTitle>Concordar com as análises da IA</AlertDialogTitle><AlertDialogDescription>Serão preenchidas somente as triagens pendentes da versão atual. Cada decisão ficará identificada com a IA escolhida e poderá ser revisada depois.</AlertDialogDescription></AlertDialogHeader><div className="ai-bulk-summary"><strong>{automaticAI.length} artigo(s) prontos para aplicação automática</strong><p>Inclui artigos com uma única análise atual e aqueles em que todas as IAs chegaram à mesma decisão.</p></div>{conflictingAI.length>0&&<div className="ai-conflicts"><h3>Divergências: escolha uma análise</h3>{conflictingAI.map((x:any)=><div className="ai-conflict-row" key={x.article.id}><div><strong>{displayTitle(x.article)}</strong><small>{x.article.doi||x.article.filename}</small></div><Select value={conflictChoices[x.article.id]||''} onValueChange={v=>setConflictChoices({...conflictChoices,[x.article.id]:v})}><SelectTrigger aria-label={'Escolher análise para '+displayTitle(x.article)}><SelectValue placeholder="Escolha qual IA seguir"/></SelectTrigger><SelectContent>{x.consensus.current.map((run:any)=><SelectItem key={run.id} value={run.id}>{run.provider}{run.model?' / '+run.model:''} — {verdict(run.decision)}</SelectItem>)}</SelectContent></Select></div>)}</div>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><Button disabled={busy||(!automaticAI.length&&!Object.values(conflictChoices).some(Boolean))} onClick={acceptAIInBulk}>Aplicar {automaticAI.length+Object.values(conflictChoices).filter(Boolean).length} decisão(ões)</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>}
 </div>
}
function TriageForm({article,protocol,guidance,busy,save,onDirty}:any){
 const valid=article.triage?.version===protocol.version;
 const [answers,setAnswers]=useState<string[]>(valid?article.triage.answers:protocol.questions.map(()=>'')),[reason,setReason]=useState(valid?article.triage.reason:'');
 const answered=answers.filter(Boolean).length,excluded=answers.includes('Não'),complete=answered===protocol.questions.length&&answers.length>0;
 return <section className="panel triage-form"><h2>Decisão humana</h2><p>Responda cada pergunta com base na referência ao lado.</p>{!protocol.approved&&<p className="notice">Aprove o PCC e as perguntas antes de registrar a triagem.</p>}
 {protocol.questions.map((q:string,i:number)=><fieldset className="question-card" key={i}><legend><span>{i+1}</span> {q}</legend>{(()=>{const guide=guidance.find((x:any)=>x.text===q);return guide?<div className="triage-guidance"><p><strong>Critério:</strong> {guide.criterion}</p><p><strong>Sim:</strong> {guide.yes}</p><p><strong>Não:</strong> {guide.no}</p><p><strong>Indeterminado:</strong> {guide.unknown}</p>{guide.example&&<p><strong>Exemplo:</strong> {guide.example}</p>}</div>:null})()}<RadioGroup className="choices" disabled={busy||!protocol.approved} value={answers[i]||''} onValueChange={value=>{setAnswers(answers.map((x,j)=>i===j?value:x));onDirty(true)}}>{['Sim','Não','Indeterminado'].map(v=><label key={v} className={'answer-option answer-'+(v==='Sim'?'yes':v==='Não'?'no':'unsure')}><RadioGroupItem value={v}/>{v}</label>)}</RadioGroup></fieldset>)}
 <div className="answer-summary"><span>Sim: {answers.filter(x=>x==='Sim').length}</span><span>Não: {answers.filter(x=>x==='Não').length}</span><span>Indeterminado: {answers.filter(x=>x==='Indeterminado').length}</span></div>
 <div className="notice"><strong>{!complete?'Responda todas as perguntas':excluded?'Resultado previsto: excluir':'Resultado previsto: manter para texto completo'}</strong><p>{excluded?'Registre a evidência que justifica o “Não”.':'A decisão será aplicada somente ao salvar.'}</p></div><label>Justificativa e evidência {excluded?'(obrigatória)':''}<Textarea value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);onDirty(true)}} placeholder="Registre o trecho ou a informação que sustenta sua decisão."/></label><div className="actions"><Button disabled={busy||!protocol.approved||!complete||(excluded&&!reason.trim())} onClick={async()=>{if(await save('triage',{article:article.id,answers,reason}))onDirty(false)}}>Salvar triagem</Button><Button variant="outline" disabled={busy} onClick={()=>{setAnswers(valid?article.triage.answers:protocol.questions.map(()=>''));setReason(valid?article.triage.reason:'');onDirty(false)}}>Descartar alterações</Button></div><small>{answered} de {protocol.questions.length} perguntas respondidas.</small></section>
}
