'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
async function request(url:string,method='GET',data?:any){const r=await fetch(url,{method,headers:data?{'content-type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const x:any=await r.json();if(!r.ok)throw Error(x.message);return x}
export default function ProjectSettings({project,busy,remove}:any){
 const [open,setOpen]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('editor'),[members,setMembers]=useState<any[]>([]),[message,setMessage]=useState('');
 const owner=project.access_role==='owner',url='/api/projects/'+project.id+'/members';
 async function load(){if(owner)setMembers(await request(url))}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[project.id,owner]);
 async function invite(){try{await request(url,'POST',{email,role});setEmail('');setMessage('Convite registrado. Envie o link do ORBIS ao pesquisador.');await load()}catch(e:any){setMessage(e.message)}}
 async function drop(value:string){try{await request(url,'DELETE',{email:value});await load()}catch(e:any){setMessage(e.message)}}
 return <><section className="panel"><h2>Equipe deste projeto</h2>{owner?<><p>Convide pesquisadores por e-mail. O projeto aparecerá somente depois que o convite for aceito.</p><div className="actions"><Input aria-label="E-mail do pesquisador" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="pesquisador@instituicao.br"/><Select value={role} onValueChange={setRole}><SelectTrigger aria-label="Função"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="editor">Colaborador</SelectItem><SelectItem value="reviewer">Revisor</SelectItem><SelectItem value="viewer">Somente leitura</SelectItem></SelectContent></Select><Button disabled={busy||!email.trim()} onClick={invite}>Convidar</Button></div>{message&&<p className="notice">{message}</p>}{!members.length&&<p className="muted">Nenhum pesquisador convidado.</p>}{members.map(m=><div className="section-top" key={m.email}><div><strong>{m.name||m.email}</strong><p>{m.email} · {m.role==='editor'?'Colaborador':m.role==='reviewer'?'Revisor':'Somente leitura'} · {m.status==='pending'?'Aguardando aceite':m.status==='accepted'?'Ativo':'Recusado'}</p></div><Button variant="outline" disabled={busy} onClick={()=>drop(m.email)}>Remover</Button></div>)}</>:<p>Sua função neste projeto é <strong>{project.access_role==='editor'?'colaborador':project.access_role==='reviewer'?'revisor':'somente leitura'}</strong>. Somente o proprietário administra a equipe.</p>}</section>{owner&&<section className="panel"><h2>Excluir projeto</h2><p>A exclusão definitiva remove os registros, PDFs e histórico deste projeto. Exporte e confira seu backup antes de excluir.</p><Button variant="outline" disabled={busy} onClick={()=>setOpen(true)}>Excluir este projeto…</Button><AlertDialog open={open} onOpenChange={setOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir definitivamente?</AlertDialogTitle><AlertDialogDescription>Esta ação não pode ser desfeita pelo site. Para confirmar, digite o nome do projeto: {project.name}</AlertDialogDescription></AlertDialogHeader><Input aria-label="Nome do projeto para confirmar exclusão" value={name} onChange={e=>setName(e.target.value)}/><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><Button variant="destructive" disabled={busy||name!==project.name} onClick={async()=>{if(await remove(name))setOpen(false)}}>Excluir dados e PDFs</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></section>}</>
}
