export type AIStage='triagem'|'pcc';
export type AIRow={index:number;text:string;answer:string;reason:string;evidence:string};
export type AIAnalysis={id:string;runId:string;stage:AIStage;provider:string;model:string;importedAt:string;protocolVersion:number;criteriaHash:string;sourceHash:string;packageId:string;corpusId:string;compatible:boolean;warning:string;decision:string;title:string;authors:string;summary:string;doi:string;questions:AIRow[];inclusion:AIRow[];exclusion:AIRow[];duplicate:boolean;duplicateOf:string;duplicateReason:string;fingerprint:string;legacyRaw?:any;};
export function fingerprint(x:any){const t=JSON.stringify(x);let h=2166136261;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
export const criteriaLines=(text:string)=>String(text||'').split(/\n+/).map(x=>x.replace(/^\s*(?:[-•*]|\d+[.)])\s*/,'').trim()).filter(Boolean);
export function criteriaFor(protocol:any,stage:AIStage){return stage==='triagem'?{stage,questions:protocol.questions,population:protocol.population,concept:protocol.concept,context:protocol.context}:{stage,population:protocol.population,concept:protocol.concept,context:protocol.context,inclusion:criteriaLines(protocol.inclusion),exclusion:criteriaLines(protocol.exclusion)}}
export const criteriaHash=(protocol:any,stage:AIStage)=>fingerprint(criteriaFor(protocol,stage));
export const articleHash=(a:any)=>fingerprint({id:a.id,title:a.title,authors:a.authors,doi:a.doi,abstract:a.abstract,filename:a.filename});
export const stageName=(s:any):AIStage|undefined=>['triagem','triage','screening'].includes(String(s).toLowerCase())?'triagem':['pcc','review','fulltext','full-text','texto completo'].includes(String(s).toLowerCase())?'pcc':undefined;
const str=(x:any,max=12000)=>typeof x==='string'?x.slice(0,max):'';
const normalize=(x:any)=>str(x,1000).normalize('NFKC').toLowerCase().replace(/[^a-z0-9]/g,'');
const doi=(x:any)=>str(x,500).replace(/^https?:\/\/(dx\.)?doi\.org\//i,'').trim().toLowerCase();
export function parseAI(text:string){let cleaned=text.replace(/^\uFEFF/,'').trim();const fenced=cleaned.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);if(fenced)cleaned=fenced[1].trim();return JSON.parse(cleaned)}
export function normalizeAIResponse(input:any,stage:AIStage){let obj=input;if(Array.isArray(obj))obj={schema:'ORBIS_AI_RESULTS_V1',items:obj};if(obj?.schema==='ORBIS_STAGE_RESPONSE_V1'&&obj.mode==='analysis'){obj={schema:'ORBIS_AI_RESULTS_V1',etapa:stage,provider:obj.provider,model:obj.model,items:[{arquivo:obj.arquivo||obj.filename||'',article_id:obj.article_id||'',resumo:obj.summary||'',triagem_nivel1:obj.questions,inclusao:obj.inclusion,exclusao:obj.exclusion}]}}if(!Array.isArray(obj?.items)&&Array.isArray(obj?.resultados))obj={...obj,schema:obj.schema||'ORBIS_AI_RESULTS_V1',items:obj.resultados};if(!Array.isArray(obj?.items)&&Array.isArray(obj?.artigos))obj={...obj,schema:obj.schema||'ORBIS_AI_RESULTS_V1',items:obj.artigos};if(!Array.isArray(obj?.items)&&Array.isArray(obj?.data?.items))obj={...obj,schema:obj.schema||'ORBIS_AI_RESULTS_V1',items:obj.data.items};return obj}

export function analysesFor(a:any,stage:AIStage):AIAnalysis[]{if(Array.isArray(a.aiAnalyses))return a.aiAnalyses.filter((x:any)=>x.stage===stage);const old=a.legacyDecision?.analisesIA?.[stage];if(!Array.isArray(old))return [];return old.map((x:any,i:number)=>{const convert=(q:any,n:number):AIRow=>({index:n+1,text:str(q.texto??q.text)||'Critério '+(n+1),answer:q.resposta|| (q.atende===true?'sim':q.atende===false?'nao':'indeterminado'),reason:str(q.motivo),evidence:typeof q.evidencia==='string'?q.evidencia:''});return {id:'legacy-'+stage+'-'+i+'-'+a.id,runId:x.runId||'legacy-'+stage+'-'+i,stage,provider:x.provider||'IA legada',model:x.model||'',importedAt:x.importedAt||'',protocolVersion:0,criteriaHash:x.criteriaHash||'',sourceHash:'',packageId:x.packageId||'',corpusId:x.corpusId||'',compatible:false,warning:'Análise do ORBIS original. Contexto preservado para conferência.',decision:['incluir','excluir','duvida'].includes(x.decisao)?x.decisao:'duvida',title:x.titulo||'',authors:x.autores||'',summary:x.resumo||'',doi:x.doi||'',questions:(x.triagemNivel1||[]).map(convert),inclusion:(x.avaliacaoDetalhada?.inclusao||[]).map(convert),exclusion:(x.avaliacaoDetalhada?.exclusao||[]).map(convert),duplicate:!!x.duplicata,duplicateOf:x.duplicata_de||'',duplicateReason:x.motivo_duplicata||'',fingerprint:fingerprint(x),legacyRaw:x}})}
export function isCurrent(x:AIAnalysis,a:any,p:any){return x.compatible&&x.protocolVersion===p.version&&x.criteriaHash===criteriaHash(p,x.stage)&&x.sourceHash===articleHash(a)}
export function aiConsensus(a:any,stage:AIStage,p:any){const history=analysesFor(a,stage),latest=new Map<string,AIAnalysis>();for(const x of history){latest.set(x.provider.toLowerCase()+'::'+(x.model.toLowerCase()||x.id),x)}const runs=[...latest.values()],current=runs.filter(x=>isCurrent(x,a,p));if(!history.length)return {label:'Sem análise',status:'none',decision:'',runs,current};if(current.length!==runs.length)return {label:'Conferir contexto',status:'stale',decision:'',runs,current};if(current.length===1)return {label:'Uma análise',status:'single',decision:current[0].decision,runs,current};if(new Set(current.map(x=>x.packageId+'|'+x.corpusId)).size>1)return {label:'Pacotes diferentes',status:'stale',decision:'',runs,current};const decisions=new Set(current.map(x=>x.decision));return decisions.size===1?{label:'Concordância',status:'agreement',decision:current[0].decision,runs,current}:{label:'Divergência',status:'conflict',decision:'duvida',runs,current}}
export function displayTitle(a:any){return a.source?.kind==='local'&&!a.titleConfirmed?([...a.aiAnalyses||[]].reverse().find((x:any)=>x.title)?.title||a.title):a.title}
export function makeAIPackage(project:any,stage:AIStage,only?:string){const protocol=project.state.protocol,articles=project.state.articles.filter((a:any)=>(!only||a.id===only)&&(stage==='triagem'||a.triage?.version===protocol.version&&a.triage.decision==='incluir'));const hash=criteriaHash(protocol,stage),corpus=fingerprint(articles.map((a:any)=>a.id).sort()),packageId=`ORBIS-WEB-${project.id}-${stage}-${protocol.version}-${corpus}-${hash}`;
 const example:any={article_id:'copiar article_id do item',arquivo:'copiar arquivo do item',source_hash:'copiar source_hash do item',etapa:stage,titulo:'',autores:'',doi:'',resumo:'Síntese apoiada nas fontes fornecidas.'};if(stage==='triagem')example.triagem_nivel1=protocol.questions.map((_:any,i:number)=>({pergunta:i+1,resposta:'indeterminado',motivo:'Justifique com título/resumo.',evidencia:''}));else{example.inclusao=criteriaLines(protocol.inclusion).map(()=>({atende:null,motivo:'Justifique com texto completo.',evidencia:'',pagina:''}));example.exclusao=criteriaLines(protocol.exclusion).map(()=>({atende:null,motivo:'Justifique com texto completo.',evidencia:'',pagina:''}));}
 return {schema:'ORBIS_AI_PACKAGE_MD_V1',project_id:project.id,etapa:stage,package_id:packageId,criteria_hash:hash,corpus_id:corpus,protocol_version:protocol.version,criteria:criteriaFor(protocol,stage),instrucoes:stage==='triagem'?'Avalie apenas título e resumo original. Responda todas as perguntas: sim, nao ou indeterminado. Ausência de informação é indeterminado. Qualquer nao fundamentado sugere excluir; sem nao, manter para texto completo. Não invente evidências ou metadados. Retorne apenas o JSON no formato_resposta, com um item por artigo; copie os identificadores. A decisão humana é independente.':'Leia os PDFs anexados ou, quando o artigo trouxer texto_completo (texto extraído do PDF; texto_truncado indica corte), leia esse texto, conferindo a correspondência de cada arquivo. Avalie cada critério separadamente (atende: true, false ou null). Justifique com evidência e página. Não invente texto completo: se um PDF estiver ausente ou ilegível, use null. Retorne o formato_resposta com os identificadores exatos. Não substitua pareceres humanos.',formato_resposta:{schema:'ORBIS_AI_RESULTS_V1',project_id:project.id,etapa:stage,package_id:packageId,criteria_hash:hash,corpus_id:corpus,provider:'identificar fornecedor',model:'identificar modelo',items:[example]},items:articles.map((a:any)=>({article_id:a.id,arquivo:a.filename,source_hash:articleHash(a),titulo_atual:a.title,autores_atuais:a.authors,doi_atual:a.doi,abstract_original:a.abstract,etapa:stage}))};
}
function rows(values:any,total:string[],tri=false):AIRow[]{if(!Array.isArray(values)||values.length!==total.length)throw Error('Quantidade de respostas diferente dos critérios.');return total.map((text,i)=>{const v=values[i];if(v===undefined)throw Error('Critério sem resposta estruturada.');const entry=v!==null&&typeof v==='object'?v:tri?{resposta:v,motivo:'Justificativa não informada pela IA.'}:{atende:v,motivo:'Justificativa não informada pela IA.'};if((entry.pergunta??entry.index??i+1)!==i+1)throw Error('Perguntas fora da ordem do protocolo.');const raw=tri?entry.resposta??entry.answer:entry.atende??entry.meets;let answer=tri?String(raw||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''):raw===true||raw==='sim'?'sim':raw===false||raw==='nao'?'nao':'indeterminado';if(!['sim','nao','indeterminado'].includes(answer)||!tri&&raw!==true&&raw!==false&&raw!=='sim'&&raw!=='nao'&&raw!=null)throw Error('Resposta inválida em um critério.');const reason=str(entry.motivo??entry.reason,4000).trim()||'Justificativa não informada pela IA; conferir antes de usar.';const ev=entry.evidencia??entry.evidence;return {index:i+1,text,answer,reason,evidence:typeof ev==='string'?str(ev,4000):ev&&typeof ev==='object'?str(ev.quote??ev.text,4000):'',...(entry.pagina||entry.page?{page:str(String(entry.pagina||entry.page),100)}:{})}})}
export function importAI(state:any,projectId:string,obj:any,stage:AIStage,mappings:Record<string,string>={}){
 obj=normalizeAIResponse(obj,stage);
 if(!['ORBIS_AI_RESULTS_V1','ORBIS_CHATGPT_RESULTS_V1'].includes(obj?.schema)||!Array.isArray(obj.items))throw Error('Use uma resposta ORBIS_AI_RESULTS_V1 com items por artigo. Uma proposta em texto não contém avaliações que possam preencher a tabela.');
 if(obj.project_id&&obj.project_id!==projectId)throw Error('Resposta pertence a outro projeto.');if(stageName(obj.etapa)&&stageName(obj.etapa)!==stage)throw Error('Resposta pertence a outra etapa.');if(obj.items.length>500)throw Error('Importe até 500 avaliações por lote.');
 const provider=str(obj.provider,150).trim()||'IA não identificada',model=str(obj.model,150).trim(),runId=crypto.randomUUID(),at=new Date().toISOString(),report:any={id:runId,at,stage,provider,model,applied:0,duplicates:0,skipped:[],matches:[]};const seen=new Set();
 for(let n=0;n<obj.items.length;n++){const item=obj.items[n];let a:any;try{if(!item||typeof item!=='object')throw Error('Item inválido.');if(stageName(item.etapa)&&stageName(item.etapa)!==stage)throw Error('Item de outra etapa.');
 const file=str(item.arquivo??item.filename,1000);let matches:any[]=[];let method='identificador';if(mappings[String(n)]){matches=state.articles.filter((x:any)=>x.id===mappings[String(n)]);method='associação manual';}else if(item.article_id){matches=state.articles.filter((x:any)=>x.id===item.article_id);}else{
 matches=state.articles.filter((x:any)=>[x.filename,x.source?.originalFilename,x.legacy?.arquivo].filter(Boolean).includes(file));method='nome exato';
 if(!matches.length&&file){matches=state.articles.filter((x:any)=>[x.filename,x.source?.originalFilename,x.legacy?.arquivo].filter(Boolean).some(f=>normalize(f)===normalize(file)));method='nome normalizado';}
 if(!matches.length&&doi(item.doi)){matches=state.articles.filter((x:any)=>doi(x.doi)===doi(item.doi));method='DOI';}}
 if(matches.length!==1)throw Error(matches.length?'Mais de um artigo corresponde; selecione o correto.':'Artigo não encontrado; selecione o registro correspondente.');a=matches[0];if(seen.has(a.id))throw Error('Artigo repetido no mesmo lote.');seen.add(a.id);
 const hash=criteriaHash(state.protocol,stage),compatible=obj.criteria_hash===hash&&!!obj.package_id&&!!obj.corpus_id&&item.source_hash===articleHash(a);
 const q=stage==='triagem'?rows(item.triagem_nivel1??item.questions,state.protocol.questions,true):[],inc=stage==='pcc'?rows(item.inclusao??item.inclusion??item.criterios?.incl,criteriaLines(state.protocol.inclusion)):[],exc=stage==='pcc'?rows(item.exclusao??item.exclusion??item.criterios?.excl,criteriaLines(state.protocol.exclusion)):[];
 if(stage==='triagem'&&!q.length||stage==='pcc'&&!inc.length)throw Error('Configure os critérios antes de importar avaliações.');
 const decision=stage==='triagem'?(q.some(x=>x.answer==='nao')?'excluir':'incluir'):exc.some(x=>x.answer==='sim')||inc.some(x=>x.answer==='nao')?'excluir':inc.every(x=>x.answer==='sim')&&exc.every(x=>x.answer==='nao')?'incluir':'duvida';
 const fp=fingerprint({stage,provider,model,item,criteria:obj.criteria_hash,package:obj.package_id});a.aiAnalyses??=[...analysesFor(a,'triagem'),...analysesFor(a,'pcc')];if(a.aiAnalyses.some((x:any)=>x.fingerprint===fp)){report.duplicates++;continue;}
 const analysis:AIAnalysis={id:crypto.randomUUID(),runId,stage,provider,model,importedAt:at,protocolVersion:state.protocol.version,criteriaHash:str(obj.criteria_hash,200),sourceHash:str(item.source_hash,200)||articleHash(a),packageId:str(obj.package_id,500),corpusId:str(obj.corpus_id,200),compatible,warning:compatible?'':'Contexto original não confirmado ou desatualizado. Visível para conferência; fora da concordância atual.',decision,title:str(item.titulo??item.title,2000),authors:str(item.autores??item.authors,2000),summary:str(item.resumo??item.summary),doi:doi(item.doi),questions:q,inclusion:inc,exclusion:exc,duplicate:item.duplicata===true,duplicateOf:str(item.duplicata_de,1000),duplicateReason:str(item.motivo_duplicata,2000),fingerprint:fp};a.aiAnalyses.push(analysis);report.applied++;report.matches.push({index:n,article:a.id,file:a.filename,method});
 }catch(e:any){report.skipped.push({index:n,file:str(item?.arquivo??item?.article_id,1000)||'Item '+(n+1),reason:e.message})}}
 state.aiImports=[...(state.aiImports||[]),report].slice(-20);return report;
}
export function removeAI(state:any,selector:any){let removed=0;if(!['article','run','provider'].includes(selector.scope))throw Error('Escolha o escopo da remoção.');if(selector.scope==='article'&&(!selector.article||!selector.analysis)||selector.scope==='run'&&!selector.runId||selector.scope==='provider'&&!selector.provider)throw Error('Identifique a análise a remover.');for(const a of state.articles){a.aiAnalyses=(a.aiAnalyses||[...analysesFor(a,'triagem'),...analysesFor(a,'pcc')]).filter((x:any)=>{const match=selector.scope==='article'?a.id===selector.article&&x.id===selector.analysis:selector.scope==='run'?x.runId===selector.runId:x.provider===selector.provider&&x.model===selector.model;if(match)removed++;return !match})}return removed}
