import {initialState,type ProjectState} from './domain';
import {analysesFor} from './ai-analysis';
const te=new TextEncoder();
export function crc(bytes:Uint8Array){let c=0xffffffff;for(const b of bytes){c^=b;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
export function legacyHash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0');}
export async function zip(files:{name:string;blob:Blob}[]){const parts:BlobPart[]=[],central:Uint8Array<ArrayBuffer>[]=[];let offset=0;for(const f of files){const name=te.encode(f.name),data=new Uint8Array(await f.blob.arrayBuffer()),c=crc(data),h=new Uint8Array(30+name.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,2048,true);v.setUint32(14,c,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);h.set(name,30);parts.push(h,f.blob);const z=new Uint8Array(46+name.length),w=new DataView(z.buffer);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,2048,true);w.setUint32(16,c,true);w.setUint32(20,data.length,true);w.setUint32(24,data.length,true);w.setUint16(28,name.length,true);w.setUint32(42,offset,true);z.set(name,46);central.push(z);offset+=h.length+data.length;}const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,files.length,true);v.setUint16(10,files.length,true);v.setUint32(12,central.reduce((n,b)=>n+b.length,0),true);v.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/vnd.orbis.project+zip'});}
export async function unpack(file:File){if(file.size>2.1*1024**3)throw Error('Backup acima do limite de 2 GB.');let pos=0;const entries=new Map<string,Blob>();while(pos+4<=file.size){const head=new Uint8Array(await file.slice(pos,pos+30).arrayBuffer()),v=new DataView(head.buffer);const sig=v.getUint32(0,true);if(sig===0x02014b50||sig===0x06054b50)break;if(sig!==0x04034b50||head.length<30)throw Error('Backup ZIP inválido.');const flags=v.getUint16(6,true),method=v.getUint16(8,true),size=v.getUint32(18,true),expanded=v.getUint32(22,true),nl=v.getUint16(26,true),xl=v.getUint16(28,true);if(flags&9||method!==0)throw Error('Importe um .orbis original sem compressão.');if(size!==expanded||size>31*1024*1024||entries.size>6000)throw Error('Entrada excede os limites do backup.');const name=await file.slice(pos+30,pos+30+nl).text();if(!name||name.startsWith('/')||name.includes('..')||name.includes('\\')||entries.has(name))throw Error('Nome interno inválido ou duplicado.');const start=pos+30+nl+xl;if(start+size>file.size)throw Error('Backup truncado.');const blob=file.slice(start,start+size);if(crc(new Uint8Array(await blob.arrayBuffer()))!==v.getUint32(14,true))throw Error('Falha de integridade: '+name);entries.set(name,blob);pos=start+size;}
 const m=JSON.parse(await entries.get('manifest.json')?.text()||'null'),p=JSON.parse(await entries.get('project.json')?.text()||'null');if(m?.schema!=='ORBIS_PROJECT_BUNDLE_V1'||m.bundle_version!==1||p?.schema!==m.schema||!Array.isArray(p.corpus)||!Array.isArray(p.pdf_index))throw Error('Formato .orbis não reconhecido.');if(m.project_hash&&m.project_hash!==legacyHash(JSON.stringify(p)))throw Error('Projeto falhou na verificação de integridade.');const names=new Set();for(const a of p.corpus){if(!a.arquivo||names.has(a.arquivo))throw Error('Artigos sem identificação única.');names.add(a.arquivo)}for(const d of p.pdf_index){if(!entries.has(d.path)||!names.has(d.arquivo))throw Error('PDF ausente ou sem artigo correspondente.');const b=entries.get(d.path)!;if(b.size>30*1024*1024||!new TextDecoder().decode(await b.slice(0,1024).arrayBuffer()).includes('%PDF-'))throw Error('PDF inválido ou acima de 30 MB.');}
 let state:ProjectState;if(p.orbis_web?.state)state=p.orbis_web.state;else{state=initialState();state.legacy=p;state.legacyManifest=m;const plain=(x:any)=>String(x||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();const c=p.criterios||{};state.protocol={...state.protocol,population:plain(c['pcc-pop']),concept:plain(c['pcc-conceito']),context:plain(c['pcc-contexto']),inclusion:plain(c.inclusao),exclusion:plain(c.exclusao),questions:(String(c['triagem-nivel1']||'').match(/<li\b[^>]*>[\s\S]*?<\/li>/gi)||[]).map(plain)};state.articles=p.corpus.map((a:any)=>({id:crypto.randomUUID(),filename:a.arquivo,doi:a.doi||'',title:a.titulo||a._titulo_informado||a.arquivo,authors:a.autores||'',year:String(a.ano||''),abstract:a.abstract||a.resumo||'',legacy:a,legacyDecision:p.decisoes?.[a.arquivo]||null}));}
 return {project:p,manifest:m,entries,state};}
export function portable(project:any){const s=project.state;const p=s.legacy?structuredClone(s.legacy):{schema:'ORBIS_PROJECT_BUNDLE_V1',bundle_version:1,app_name:'ORBIS',criterios:{},deduplicacao:{pairs:{},history:[]},configuracoes:{triagem_policy:'humana'},planejamento:null,ia_central:null,indexeddb_textos:[]};p.exported_at=new Date().toISOString();p.corpus=s.articles.map((a:any)=>({...a.legacy,arquivo:a.filename,tipo:'artigo',doi:a.doi,titulo:a.title,_titulo_informado:a.title,autores:a.authors,ano:a.year,abstract:a.abstract}));p.decisoes=p.decisoes||{};for(const a of s.articles)if(a.triage)p.decisoes[a.filename]={...p.decisoes[a.filename],decisaoTriagem:a.triage.decision,origemTriagem:'manual',nota:a.triage.reason};for(const a of s.articles){p.decisoes[a.filename]??={};p.decisoes[a.filename].analisesIA={triagem:analysesFor(a,'triagem').map(legacyAI),pcc:analysesFor(a,'pcc').map(legacyAI)};}p.pdf_index=[];p.orbis_web={version:1,name:project.name,state:s,searches:project.searches||[],attempts:project.attempts||[]};return p;}
export function download(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}

function legacyAI(x:any){return {...x.legacyRaw,...x,decisao:x.decision,titulo:x.title,autores:x.authors,resumo:x.summary,triagemNivel1:x.questions.map((q:any)=>({pergunta:q.index,resposta:q.answer,motivo:q.reason,evidencia:q.evidence})),avaliacaoDetalhada:{inclusao:x.inclusion.map((q:any)=>({atende:q.answer==='sim'?true:q.answer==='nao'?false:null,motivo:q.reason,evidencia:q.evidence})),exclusao:x.exclusion.map((q:any)=>({atende:q.answer==='sim'?true:q.answer==='nao'?false:null,motivo:q.reason,evidencia:q.evidence}))},criterios:{incl:(x.stage==='triagem'?x.questions:x.inclusion).map((q:any)=>q.answer==='sim'),excl:(x.stage==='triagem'?x.questions:x.exclusion).map((q:any)=>q.answer===(x.stage==='triagem'?'nao':'sim'))}}}
