import type {PlanItem} from './protocol-planner';
const item=(kind:string,text:string,extra:any={}):PlanItem=>({id:crypto.randomUUID(),kind,text,criterion:'',yes:'',no:'',unknown:'Informação ausente ou ambígua: manter para leitura do texto completo.',example:'',reason:'',status:'rascunho',...extra});
const entities=(x:string)=>x.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'");
async function docxText(file:File){const bytes=new Uint8Array(await file.arrayBuffer()),v=new DataView(bytes.buffer);let found:any;for(let p=0;p+46<=bytes.length;){if(v.getUint32(p,true)!==0x02014b50){p++;continue}const method=v.getUint16(p+10,true),size=v.getUint32(p+20,true),nl=v.getUint16(p+28,true),xl=v.getUint16(p+30,true),cl=v.getUint16(p+32,true),offset=v.getUint32(p+42,true),name=new TextDecoder().decode(bytes.slice(p+46,p+46+nl));if(name==='word/document.xml')found={method,size,offset};p+=46+nl+xl+cl}if(!found)throw Error('O DOCX não contém o texto principal.');const o=found.offset;if(v.getUint32(o,true)!==0x04034b50)throw Error('Estrutura DOCX inválida.');const start=o+30+v.getUint16(o+26,true)+v.getUint16(o+28,true),packed=bytes.slice(start,start+found.size);let raw:Uint8Array;if(found.method===0)raw=packed;else if(found.method===8){const stream=new Blob([packed]).stream().pipeThrough(new DecompressionStream('deflate-raw'));raw=new Uint8Array(await new Response(stream).arrayBuffer())}else throw Error('Compressão DOCX não suportada.');return entities(new TextDecoder().decode(raw).replace(/<w:tab\/?[^>]*>/g,'\t').replace(/<\/w:p>/g,'\n').replace(/<[^>]+>/g,' ').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').trim())}
export async function readProtocolSource(file:File){if(file.size>15*1024*1024)throw Error(file.name+': limite de 15 MB.');if(/\.docx$/i.test(file.name))return docxText(file);if(/\.(txt|md)$/i.test(file.name))return file.text();if(/\.json$/i.test(file.name))return JSON.stringify(JSON.parse(await file.text()),null,2);throw Error(file.name+': use DOCX, TXT, MD ou JSON.')}
export function parseProtocolResponse(text:string){
 let cleaned=text.replace(/^\uFEFF/,'').trim();const fenced=cleaned.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);if(fenced)cleaned=fenced[1].trim();
 try{return {value:JSON.parse(cleaned),repaired:false,repairs:[] as string[]}}
 catch(first:any){
  const repairs:string[]=[];let lines=cleaned.split(/\r?\n/);
  lines=lines.map((line,i)=>{const bare=line.match(/^(\s+)(\S.*?)(,?)\s*$/);if(bare&&!/^["}\]]/.test(bare[2])&&/"reason"\s*:/.test(lines[i-1]||'')&&/"yes"\s*:/.test(lines[i+1]||'')){repairs.push(`Linha ${i+1}: propriedade criterion restaurada.`);return bare[1]+'"criterion": '+JSON.stringify(bare[2].trim().replace(/,$/,''))+','}return line});
  let repaired=lines.join('\n').replace(/,\s*([}\]])/g,'$1');if(repaired!==lines.join('\n'))repairs.push('Vírgula final removida.');
  try{return {value:JSON.parse(repaired),repaired:true,repairs}}
  catch(second:any){const match=String(second.message).match(/position\s+(\d+)/i);const pos=match?Number(match[1]):-1;const before=pos>=0?repaired.slice(0,pos):'';const line=pos>=0?before.split('\n').length:undefined;const column=pos>=0?before.length-before.lastIndexOf('\n'):undefined;const excerpt=line?repaired.split('\n').slice(Math.max(0,line-2),line+1).join('\n'):'';throw Error(`JSON inválido${line?` na linha ${line}, coluna ${column}`:''}. ${excerpt?`Trecho: ${excerpt.slice(0,500)}`:'Revise aspas, vírgulas e nomes das propriedades.'}`)}
 }
}
const headings:{kind:string;names:string[]}[]=[{kind:'objetivo',names:['objective','objectives','objetivo','objetivos','aim','aims']},{kind:'pergunta',names:['review question','research question','pergunta de pesquisa','questão de pesquisa','pergunta proposta']},{kind:'populacao',names:['participants','participant','population','população','participantes']},{kind:'conceito',names:['concept','conceito']},{kind:'contexto',names:['context','contexto']},{kind:'inclusao',names:['inclusion criteria','criteria for inclusion','critérios de inclusão','critério de inclusão','eligibility criteria']},{kind:'exclusao',names:['exclusion criteria','criteria for exclusion','critérios de exclusão','critério de exclusão']},{kind:'questao',names:['screening questions','triage questions','perguntas de triagem','questões de triagem']}];
const clean=(x:string)=>x.replace(/^\s*[-–—•\d.)]+\s*/,'').trim();
export function inferProtocolItems(sources:{name:string;text:string}[],stage:'pcc'|'triagem'){
 const collected=new Map<string,string[]>(),stops=['types of sources','tipos de fontes','search strategy','estratégia de busca','methods','métodos','results','resultados','discussion','discussão','data extraction','extração de dados','study selection','seleção dos estudos'];
 for(const source of sources){const lines=source.text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let active='';for(const line of lines){const normalized=line.toLocaleLowerCase().replace(/[:.]$/,'').trim(),head=headings.find(h=>h.names.includes(normalized));if(head){active=head.kind;continue}const inline=headings.map(h=>({h,m:h.names.map(n=>line.match(new RegExp('^'+n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*[:–—-]\\s*(.+)$','i'))).find(Boolean)})).find(x=>x.m);if(inline?.m){active=inline.h.kind;const value=clean(inline.m[1]);if(value)(collected.get(active)||collected.set(active,[]).get(active)!).push(value);continue}if(stops.includes(normalized)){active='';continue}if(active){const value=clean(line);if(value)(collected.get(active)||collected.set(active,[]).get(active)!).push(value)}}}
 if(stage==='triagem')return (collected.get('questao')||[]).slice(0,30).map(text=>item('questao',text,{criterion:'Definido nos documentos importados',yes:'O título ou resumo confirma o critério.',no:'O título ou resumo demonstra incompatibilidade com o critério.',example:'Quando a informação não estiver disponível, responder Indeterminado.'}));
 const out:PlanItem[]=[];for(const kind of ['objetivo','pergunta','populacao','conceito','contexto'])out.push(item(kind,(collected.get(kind)||[]).join('\n')));for(const kind of ['inclusao','exclusao'])for(const text of collected.get(kind)||[])out.push(item(kind,text));return out
}
export function buildEligibilityFilter(items:PlanItem[]){
 const rows:{origin:string;question:string;yes:string;no:string;unknown:string}[]=[];
 const first=(kind:string)=>items.find(x=>x.kind===kind)?.text.trim();
 for(const [kind,label] of [['populacao','população'],['conceito','conceito'],['contexto','contexto']] as const){const value=first(kind);if(value)rows.push({origin:label,question:`O título ou resumo indica compatibilidade com ${label}: ${value}?`,yes:'Mantém para a próxima verificação.',no:'Exclui por incompatibilidade com '+label+'.',unknown:'Mantém para leitura do texto completo.'})}
 for(const x of items.filter(x=>x.kind==='inclusao'&&x.text.trim()))rows.push({origin:'inclusão',question:`O estudo atende ao critério de inclusão: ${x.text.trim()}?`,yes:'Mantém para a próxima verificação.',no:'Exclui por não atender ao critério.',unknown:'Mantém para leitura do texto completo.'});
 for(const x of items.filter(x=>x.kind==='exclusao'&&x.text.trim()))rows.push({origin:'exclusão',question:`O estudo está livre do critério de exclusão: ${x.text.trim()}?`,yes:'Mantém para a próxima verificação.',no:'Exclui porque o critério está presente.',unknown:'Mantém para leitura do texto completo.'});
 return rows.slice(0,30);
}
export const exclusionReasons=['População incompatível','Conceito incompatível','Contexto incompatível','Tipo de publicação inelegível','Ausência de dados necessários','Estudo exclusivamente animal','Dados humanos não separáveis','Texto completo indisponível','Registro duplicado','Informação insuficiente','Outro motivo justificado'];
