import {fingerprint,criteriaLines} from './ai-analysis';
import {normalizedPolicies} from './document-type';
export type PlanStage='pcc'|'triagem';
export type PlanItem={id:string;kind:string;text:string;criterion:string;yes:string;yesDecision:'include'|'exclude';no:string;noDecision:'include'|'exclude';unknown:string;unknownDecision:'include'|'exclude';example:string;reason:string;status:'rascunho'|'aprovado';approvedHash?:string};
export type PlanState={schema:'ORBIS_PLANNER_V1';documentTypes:any[];stages:Record<PlanStage,{items:PlanItem[];requests:any[];inbox:any[];messages:any[];simulations:any[];appliedHash?:string}>;history:any[]};
export const itemHash=(i:PlanItem)=>fingerprint([i.kind,i.text,i.criterion,i.yes,i.yesDecision||'include',i.no,i.noDecision||'exclude',i.unknown,i.unknownDecision||'include',i.example]);
export const pccHash=(p:any)=>fingerprint({population:p.population,concept:p.concept,context:p.context,inclusion:p.inclusion,exclusion:p.exclusion,documentTypes:normalizedPolicies(p.documentTypes)});
export function seeded(stage:PlanStage,p:any):PlanItem[]{const make=(kind:string,text='',index=-1):PlanItem=>({id:crypto.randomUUID(),kind,text,criterion:'',yes:'',yesDecision:p.questionRules?.[index]?.yesDecision==='exclude'?'exclude':'include',no:'',noDecision:p.questionRules?.[index]?.noDecision==='include'?'include':'exclude',unknown:'Informação ausente ou ambígua: manter para texto completo.',unknownDecision:p.questionRules?.[index]?.unknownDecision==='exclude'?'exclude':'include',example:'',reason:'',status:'rascunho'});if(stage==='triagem')return p.questions.map((x:string,i:number)=>make('questao',x,i));return [make('objetivo'),make('pergunta'),make('populacao',p.population),make('conceito',p.concept),make('contexto',p.context),...criteriaLines(p.inclusion).map((x:string)=>make('inclusao',x)),...criteriaLines(p.exclusion).map((x:string)=>make('exclusao',x))]}
export function newPlanner(protocol:any,legacy?:any):PlanState{const out:PlanState={schema:'ORBIS_PLANNER_V1',documentTypes:normalizedPolicies(legacy?.documentTypes||protocol.documentTypes),stages:{pcc:{items:seeded('pcc',protocol),requests:[],inbox:[],messages:[],simulations:[]},triagem:{items:seeded('triagem',protocol),requests:[],inbox:[],messages:[],simulations:[]}},history:[]};if(legacy?.schema==='ORBIS_PLANNER_V1'&&legacy.stages){for(const stage of ['pcc','triagem'] as PlanStage[]){const st=legacy.stages[stage];if(!Array.isArray(st?.items))continue;out.stages[stage].items=st.items.slice(0,80).map((x:any,i:number)=>({...seeded(stage,protocol)[i]||seeded(stage,protocol)[0],id:typeof x.id==='string'?x.id:crypto.randomUUID(),kind:x.kind,text:String(x.text||''),criterion:String(x.criterion||''),yes:String(x.yes||''),yesDecision:x.yesDecision==='exclude'?'exclude':'include',no:String(x.no||''),noDecision:x.noDecision==='include'?'include':'exclude',unknown:String(x.unknown||''),unknownDecision:x.unknownDecision==='exclude'||!x.unknownDecision&&/exclu/i.test(String(x.unknown||''))?'exclude':'include',example:String(x.example||''),reason:String(x.reason||''),status:x.status==='aprovado'?'aprovado':'rascunho',approvedHash:x.approvedHash}));out.stages[stage].messages=Array.isArray(st.messages)?st.messages.slice(-20):[]}out.history=Array.isArray(legacy.history)?legacy.history.slice(-20):[]}return out}
export function validatePlanner(p:any){p.documentTypes=normalizedPolicies(p.documentTypes);if(p?.schema!=='ORBIS_PLANNER_V1'||!p.stages||!Array.isArray(p.history)||p.history.length>100)throw Error('Planejamento inválido.');for(const stage of ['pcc','triagem'] as PlanStage[]){const x=p.stages[stage];if(!x||!Array.isArray(x.items)||x.items.length>80||!Array.isArray(x.inbox)||x.inbox.length>80||!Array.isArray(x.requests)||x.requests.length>15||!Array.isArray(x.messages)||x.messages.length>50||!Array.isArray(x.simulations)||x.simulations.length>20)throw Error('Limites do planejamento excedidos.');const ids=new Set();for(const item of x.items){if(!item||typeof item.id!=='string'||ids.has(item.id)||typeof item.text!=='string'||item.text.length>4000||!['rascunho','aprovado'].includes(item.status)||!['objetivo','pergunta','populacao','conceito','contexto','inclusao','exclusao','questao'].includes(item.kind)||stage==='triagem'&&item.kind!=='questao'||stage==='pcc'&&item.kind==='questao')throw Error('Item de planejamento inválido.');ids.add(item.id);if(!['include','exclude'].includes(item.yesDecision))item.yesDecision='include';if(!['include','exclude'].includes(item.noDecision))item.noDecision='exclude';if(!['include','exclude'].includes(item.unknownDecision))item.unknownDecision=/exclu/i.test(item.unknown)?'exclude':'include';for(const k of ['criterion','yes','no','unknown','example','reason'])if(typeof item[k]!=='string'||item[k].length>4000)throw Error('Campo do planejamento inválido.')}}return p as PlanState}
export const contextHash=(items:PlanItem[],protocol:any)=>fingerprint({items:items.map(i=>[i.id,i.kind,i.text,i.criterion,i.yes,i.no,i.unknown,i.example,i.status]),protocol:pccHash(protocol)});
export function suggestedTriageItems(items:PlanItem[]):PlanItem[]{
 const rows:{origin:string;question:string;yes:string;no:string;unknown:string}[]=[];
 const first=(kind:string)=>items.find(x=>x.kind===kind)?.text.trim();
 for(const [kind,label] of [['populacao','população'],['conceito','conceito'],['contexto','contexto']] as const){const value=first(kind);if(value)rows.push({origin:label,question:`O título ou resumo indica compatibilidade com ${label}: ${value}?`,yes:'Mantém para a próxima verificação.',no:'Exclui por incompatibilidade com '+label+'.',unknown:'Mantém para leitura do texto completo.'})}
 for(const x of items.filter(x=>x.kind==='inclusao'&&x.text.trim()))rows.push({origin:'critério de inclusão',question:`O estudo atende ao critério de inclusão: ${x.text.trim()}?`,yes:'Mantém para a próxima verificação.',no:'Exclui por não atender ao critério.',unknown:'Mantém para leitura do texto completo.'});
 for(const x of items.filter(x=>x.kind==='exclusao'&&x.text.trim()))rows.push({origin:'critério de exclusão',question:`O estudo está livre do critério de exclusão: ${x.text.trim()}?`,yes:'Mantém para a próxima verificação.',no:'Exclui porque o critério está presente.',unknown:'Mantém para leitura do texto completo.'});
 return rows.slice(0,30).map(x=>({id:crypto.randomUUID(),kind:'questao',text:x.question,criterion:x.origin,yes:x.yes,yesDecision:'include',no:x.no,noDecision:'exclude',unknown:x.unknown,unknownDecision:'include',example:'Quando título e resumo não forem suficientes, responder Indeterminado.',reason:'Pergunta sugerida automaticamente a partir do PCC aplicado.',status:'rascunho'}));
}
export function applyPlanner(p:PlanState,stage:PlanStage,protocol:any){
 const items=p.stages[stage].items;
 if(!items.length||items.some(i=>!i.text.trim()||i.status!=='aprovado'||i.approvedHash!==itemHash(i)))throw Error('Preencha e aprove cada item da etapa antes de aplicar.');
 if(stage==='pcc'){
  const singletonKinds=['objetivo','pergunta','populacao','conceito','contexto'];
  const labels:Record<string,string>={objetivo:'objetivo',pergunta:'pergunta de pesquisa',populacao:'população',conceito:'conceito',contexto:'contexto'};
  const missing=singletonKinds.filter(kind=>!items.some(i=>i.kind===kind&&i.text.trim()));
  if(missing.length)throw Error('Ainda falta preencher: '+missing.map(kind=>labels[kind]).join(', ')+'.');
  if(!items.some(i=>i.kind==='inclusao'&&i.text.trim())||!items.some(i=>i.kind==='exclusao'&&i.text.trim()))throw Error('Inclua pelo menos um critério de inclusão e um de exclusão.');
  const normalized=[...singletonKinds.map(kind=>items.filter(i=>i.kind===kind).at(-1)!),...items.filter(i=>i.kind==='inclusao'||i.kind==='exclusao')];
  p.stages.pcc.items=normalized;
  const next={...protocol,population:normalized.find(i=>i.kind==='populacao')!.text,concept:normalized.find(i=>i.kind==='conceito')!.text,context:normalized.find(i=>i.kind==='contexto')!.text,inclusion:normalized.filter(i=>i.kind==='inclusao').map(i=>i.text).join('\n'),exclusion:normalized.filter(i=>i.kind==='exclusao').map(i=>i.text).join('\n'),documentTypes:normalizedPolicies(p.documentTypes),approved:false,version:protocol.version+1};
  p.stages.pcc.appliedHash=pccHash(next);p.stages.triagem.items=suggestedTriageItems(normalized);p.stages.triagem.inbox=[];p.stages.triagem.simulations=[];delete p.stages.triagem.appliedHash;return next;
 }
 if(p.stages.pcc.appliedHash!==pccHash(protocol))throw Error('Aplique primeiro o PCC atual. Atualizações no PCC exigem nova aprovação.');
 if(items.length>30)throw Error('Limite de 30 perguntas.');
 for(const i of items)if(!i.criterion.trim()||!i.yes.trim()||!i.no.trim()||!i.unknown.trim())throw Error('Cada pergunta precisa de origem e orientação para Sim, Não e Indeterminado.');
 return {...protocol,questions:items.map(i=>i.text),questionRules:items.map(i=>({yesDecision:i.yesDecision||'include',noDecision:i.noDecision||'exclude',unknownDecision:i.unknownDecision||'include',criterion:i.criterion,yes:i.yes,no:i.no,unknown:i.unknown})),approved:true,version:protocol.version+1};
}
