import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export class ApiError extends Error {constructor(public status:number,message:string){super(message)}}
export function database(){const db=(env as any).DB as D1Database;if(!db)throw new ApiError(503,'Banco indisponível. Seus dados não foram alterados.');return db;}
export function bucket(){const b=(env as any).BUCKET as R2Bucket;if(!b)throw new ApiError(503,'Armazenamento indisponível.');return b;}
export async function identity(request:Request){const user=await getChatGPTUser();if(!user)throw new ApiError(401,'Entre com sua conta para continuar.');if(!['GET','HEAD'].includes(request.method)){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new ApiError(403,'Origem não autorizada.');}return user.userId;}
export async function profile(request:Request){const user=await getChatGPTUser();if(!user)throw new ApiError(401,'Entre com sua conta para continuar.');if(!['GET','HEAD'].includes(request.method)){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new ApiError(403,'Origem não autorizada.');}return {id:user.userId,email:user.email.trim().toLowerCase(),name:user.displayName}}
export async function owned(id:string,actor:string){const p=await database().prepare("SELECT p.*,CASE WHEN p.owner=? THEN 'owner' ELSE m.role END access_role FROM projects p LEFT JOIN project_members m ON m.project=p.id AND m.user_id=? AND m.status='accepted' WHERE p.id=? AND (p.owner=? OR m.user_id=?)").bind(actor,actor,id,actor,actor).first<any>();if(!p)throw new ApiError(404,'Projeto não encontrado ou sem permissão.');return p;}
export function requireRole(p:any,roles:string[]){if(!roles.includes(p.access_role))throw new ApiError(403,'Sua função neste projeto não permite esta alteração.');}
export async function body(request:Request){const raw=await request.text();if(raw.length>1800000)throw new ApiError(413,'Conteúdo muito grande para esta operação.');try{return JSON.parse(raw)}catch{throw new ApiError(400,'Dados inválidos.')}}
export function ok(data:any,status=200){return Response.json(data,{status,headers:{'cache-control':'no-store'}})}
export function fail(e:any){console.error('ORBIS API:',e.message);return ok({message:e instanceof ApiError?e.message:'Não foi possível concluir. Tente novamente; o projeto foi preservado.'},e instanceof ApiError?e.status:500)}
export async function commit(p:any,actor:string,state:any,action:string){const db=database(),at=new Date().toISOString(),snapshot=JSON.stringify(state);if(snapshot.length>1800000)throw new ApiError(413,'Projeto excede o limite desta versão. Exporte um backup.');const old=JSON.parse(p.state);const changed=state.articles.filter((a:any)=>JSON.stringify(a)!==JSON.stringify(old.articles.find((x:any)=>x.id===a.id)));const auditSnapshot=JSON.stringify({protocol:state.protocol,notes:state.notes,articles:changed,aiImports:state.aiImports,planner:state.planner,importPending:state.importPending});const results=await db.batch([
 db.prepare('INSERT INTO events(id,project,actor,action,revision,created,snapshot) SELECT ?,id,?,?,revision+1,?,? FROM projects WHERE id=? AND revision=?').bind(crypto.randomUUID(),actor,action,at,auditSnapshot,p.id,p.revision),
 db.prepare('UPDATE projects SET state=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(snapshot,at,p.id,p.revision)
]);if(!results[1].meta.changes)throw new ApiError(409,'O projeto mudou em outra aba. Atualize antes de salvar.');return {revision:p.revision+1,state,updated:at};}
