import {identity,owned,database,bucket,body,ok,fail,ApiError,requireRole} from '@/lib/server';
import {resolveArticle} from '@/lib/article-resolver';
import {retrievePdf,MAX_PDF_BYTES} from '@/lib/pdf-transfer';
const QUOTA=2*1024*1024*1024;
export async function GET(r:Request,{params}:any){try{const actor=await identity(r),{id}=await params;await owned(id,actor);const doc=await database().prepare("SELECT * FROM documents WHERE project=? AND id=? AND status='ready'").bind(id,new URL(r.url).searchParams.get('document')||'').first<any>();if(!doc)throw new ApiError(404,'PDF não encontrado.');const object=await bucket().get(doc.key);if(!object)throw new ApiError(404,'Arquivo indisponível.');return new Response(object.body,{headers:{'content-type':'application/pdf','content-disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(doc.name),'cache-control':'private, no-store','x-content-type-options':'nosniff'}})}catch(e){return fail(e)}}
export async function POST(r:Request,{params}:any){let reserved=0,project='',key='',docId='',attemptArticle='';try{const actor=await identity(r),{id}=await params;project=id;const p=await owned(id,actor);requireRole(p,['owner','editor']);if(p.archived)throw new ApiError(409,'Projeto em exclusão.');const s=JSON.parse(p.state),u=new URL(r.url);let articleId=u.searchParams.get('article');attemptArticle=articleId||'';let bytes:Uint8Array;
if(r.headers.get('content-type')?.includes('application/pdf')){
 const reader=r.body?.getReader();if(!reader)throw new ApiError(400,'Arquivo vazio.');let size=0;const chunks:Uint8Array[]=[];while(true){const v=await reader.read();if(v.done)break;size+=v.value.length;if(size>MAX_PDF_BYTES){await reader.cancel();throw new ApiError(413,'Limite de 30 MB por PDF.');}chunks.push(v.value)}bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}
}else{
 const b=await body(r);articleId=b.article;attemptArticle=articleId||'';const a=s.articles.find((x:any)=>x.id===articleId);if(!a?.doi)throw new ApiError(400,'Selecione um registro com DOI.');const found=await resolveArticle(a.doi);const reasons=[];let result:Uint8Array|undefined;const start=Date.now();for(const url of (found.pdfUrls||[]).slice(0,8)){const left=55000-(Date.now()-start);if(left<=0)break;try{result=await retrievePdf(url,AbortSignal.timeout(Math.min(14000,left)));break}catch(e:any){reasons.push(new URL(url).hostname+': '+e.message)}}if(!result)throw new ApiError(422,reasons.join('; ')||found.reasonDetail||'PDF gratuito não localizado.');bytes=result;
}
const a=s.articles.find((x:any)=>x.id===articleId);if(!a)throw new ApiError(404,'Artigo não pertence ao projeto.');if(!new TextDecoder().decode(bytes.subarray(0,1024)).includes('%PDF-'))throw new ApiError(400,'O arquivo não tem assinatura PDF válida.');const db=database();const existing=await db.prepare("SELECT id FROM documents WHERE project=? AND article=? AND status='ready'").bind(id,articleId).first<any>();if(existing)return ok({id:existing.id,existing:true});const quota=await db.prepare('UPDATE projects SET bytes=bytes+? WHERE id=? AND owner=? AND bytes+?<=?').bind(bytes.length,id,actor,bytes.length,QUOTA).run();if(!quota.meta.changes)throw new ApiError(413,'O projeto atingiu o limite de 2 GB.');reserved=bytes.length;docId=crypto.randomUUID();key=id+'/'+docId;const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes).buffer))).map(b=>b.toString(16).padStart(2,'0')).join('');
if(a.source?.localHash&&a.source.localHash!==hash)throw new ApiError(400,'Selecione o mesmo PDF usado para criar este registro.');
await db.prepare('INSERT INTO documents(id,project,article,key,name,size,hash,status,created) VALUES(?,?,?,?,?,?,?,?,?)').bind(docId,id,articleId,key,a.filename||'artigo.pdf',bytes.length,hash,'uploading',new Date().toISOString()).run();await bucket().put(key,bytes,{httpMetadata:{contentType:'application/pdf'}});await db.prepare("UPDATE documents SET status='ready' WHERE id=? AND project=?").bind(docId,id).run();reserved=0;await db.prepare('INSERT INTO pdf_attempts(id,project,article,status,reason,created) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,articleId,'saved','PDF armazenado no projeto',new Date().toISOString()).run();return ok({id:docId,size:bytes.length,hash});
}catch(e:any){if(attemptArticle&&project&&e instanceof ApiError&&![401,403,404].includes(e.status)){try{await database().prepare('INSERT INTO pdf_attempts(id,project,article,status,reason,created) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),project,attemptArticle,'pending',e.message,new Date().toISOString()).run()}catch{}}if(reserved){try{if(key)await bucket().delete(key);if(docId)await database().prepare('DELETE FROM documents WHERE id=? AND project=?').bind(docId,project).run();await database().prepare('UPDATE projects SET bytes=bytes-? WHERE id=?').bind(reserved,project).run()}catch{console.error('Upload cleanup pending',docId)}}return fail(e)}}
